import { describe, expect, it } from "vitest";
import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repo = fileURLToPath(new URL("..", import.meta.url));

/**
 * Loop's findings are files, and `docs/LOOP.md` and the roadmap's Loop counts
 * are views of them — the same arrangement as the roadmap itself, and it needs
 * the same guard, or the view is the first thing to fall behind.
 */
describe("the Loop findings are derived, not written", () => {
  it("is current — run `node scripts/loop.mjs render`", () => {
    const out = execFileSync("node", [`${repo}/scripts/loop.mjs`, "render", "--check"], {
      cwd: repo,
      encoding: "utf8",
      timeout: 60_000,
    });
    expect(out).toContain("is current");
  }, 120_000);

  it("says it is generated, in the file itself, and where to edit instead", () => {
    const page = readFileSync(`${repo}/docs/LOOP.md`, "utf8");
    expect(page.startsWith("<!-- Generated by scripts/loop.mjs")).toBe(true);
    expect(page).toContain("edit the finding in docs/loop/");
  });

  it("pins the workspace the findings came from", () => {
    const cfg = JSON.parse(readFileSync(`${repo}/.stitch.json`, "utf8"));
    expect(cfg.workspace, "the scripts refuse to guess a workspace").toMatch(/^[0-9a-f-]{36}$/);
  });

  it("puts every finding's project on the roadmap, or says it is new", () => {
    /* A finding that names a project directory that is not there is pointing at
       nothing, and `findingProblems` says so in `render --check`. This reads the
       other half: that the roadmap actually prints the counts. */
    const roadmap = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    const dir = path.join(repo, "docs/loop");
    const any = existsSync(dir) && readdirSync(dir).some((n) => n.endsWith(".md"));
    if (any) expect(roadmap).toContain("[Loop findings](LOOP.md)");
  });

  it("keeps the installer's address out of the repository — it is a read token, and this repo is public", () => {
    /* The installer URL carries a token for a bucket that does not allow public
       reads, so it lives in a secret. This walks what is committed under
       .github/ and the docs for the host it would be spelled with. */
    const roots = [".github", "docs", "scripts", "AGENTS.md"];
    const offenders: string[] = [];
    const walk = (p: string) => {
      const full = path.join(repo, p);
      if (!existsSync(full)) return;
      if (readdirSyncSafe(full)) for (const n of readdirSyncSafe(full)!) walk(path.join(p, n));
      else if (/\.(md|ya?ml|mjs|ts|json|sh)$/.test(p) && /firebasestorage\.googleapis\.com[^\s"']*token=/.test(readFileSync(full, "utf8"))) offenders.push(p);
    };
    roots.forEach(walk);
    expect(offenders, "a download token is committed here; move it to a secret and rotate it").toEqual([]);
  });

  it("keel's own loop test passes — keel ships it, and CI runs vitest, not node --test", () => {
    /* keel-loop.yml (keel practice `loop`) replaced isocan's loop.yml on
       5 Oct 2026; the guards that lived here (pull never decides, Loop is
       enabled in a fresh CLI, the key reaches the CLI as STITCH_API_KEY) are
       keel's now, held by its tests/loop.test.mjs and its own workflow
       tests. This runs that file so isocan's gate still reads it. */
    const out = spawnSync(process.execPath, ["--test", `${repo}/tests/loop.test.mjs`], { cwd: repo, encoding: "utf8" });
    expect(out.status, out.stdout + out.stderr).toBe(0);
  });
});

function readdirSyncSafe(p: string): string[] | null {
  try {
    return readdirSync(p);
  } catch {
    return null;
  }
}
