import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repo = fileURLToPath(new URL("..", import.meta.url));

/**
 * Loop's findings are files, and `docs/LOOP.md` and the roadmap's Loop counts
 * are views of them — the same arrangement as the roadmap itself, and it needs
 * the same guard, or the view is the first thing to fall behind.
 */
describe("the Loop findings are derived, not written", () => {
  it("is current — run `node scripts/loop.mjs render`", () => {
    const out = execFileSync("node", [`${repo}/scripts/loop.mjs`, "render", "--check"], {
      cwd: repo,
      encoding: "utf8",
      timeout: 60_000,
    });
    expect(out).toContain("is current");
  }, 120_000);

  it("says it is generated, in the file itself, and where to edit instead", () => {
    const page = readFileSync(`${repo}/docs/LOOP.md`, "utf8");
    expect(page.startsWith("<!-- Generated by scripts/loop.mjs")).toBe(true);
    expect(page).toContain("edit the finding in docs/loop/");
  });

  it("pins the workspace the findings came from", () => {
    const cfg = JSON.parse(readFileSync(`${repo}/.stitch.json`, "utf8"));
    expect(cfg.workspace, "the scripts refuse to guess a workspace").toMatch(/^[0-9a-f-]{36}$/);
  });

  it("puts every finding's project on the roadmap, or says it is new", () => {
    /* A finding that names a project directory that is not there is pointing at
       nothing, and `findingProblems` says so in `render --check`. This reads the
       other half: that the roadmap actually prints the counts. */
    const roadmap = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    const dir = path.join(repo, "docs/loop");
    const any = existsSync(dir) && readdirSync(dir).some((n) => n.endsWith(".md"));
    if (any) expect(roadmap).toContain("[Loop findings](LOOP.md)");
  });

  it("never sends a decision it was not asked to — decide is not what a pull or prove calls", () => {
    /* `decide` pushes to a workspace other people read. The script's pull,
       prove and propose paths must not reach it; this holds the line in the
       source, where an edit would cross it. */
    const script = readFileSync(`${repo}/scripts/loop.mjs`, "utf8");
    const proveFn = script.slice(script.indexOf("function proveUntriaged"), script.indexOf("// ── commands"));
    const pull = script.slice(script.indexOf('case "pull"'), script.indexOf('case "list"'));
    const propose = script.slice(script.indexOf('case "propose"'), script.indexOf('case "decide"'));
    const proveCmd = script.slice(script.indexOf('case "prove"'), script.indexOf('case "render"'));
    expect(pull, "pull runs proveUntriaged over new findings unless --no-prove is set").toContain("proveUntriaged()");
    for (const body of [proveFn, pull, propose, proveCmd]) {
      expect(body, "these commands only read Loop, prove against the code, and write files").not.toMatch(
        /await push\(|upsertContext|stitch\(\[\s*"(dismiss|create|delete|edit)"/,
      );
    }
  });

  it("keeps the installer's address out of the repository — it is a read token, and this repo is public", () => {
    /* The installer URL carries a token for a bucket that does not allow public
       reads, so it lives in a secret. This walks what is committed under
       .github/ and the docs for the host it would be spelled with. */
    const roots = [".github", "docs", "scripts", "AGENTS.md"];
    const offenders: string[] = [];
    const walk = (p: string) => {
      const full = path.join(repo, p);
      if (!existsSync(full)) return;
      if (readdirSyncSafe(full)) for (const n of readdirSyncSafe(full)!) walk(path.join(p, n));
      else if (/\.(md|ya?ml|mjs|ts|json|sh)$/.test(p) && /firebasestorage\.googleapis\.com[^\s"']*token=/.test(readFileSync(full, "utf8"))) offenders.push(p);
    };
    roots.forEach(walk);
    expect(offenders, "a download token is committed here; move it to a secret and rotate it").toEqual([]);
  });

  it("the nightly pull reads Loop and files findings, and nothing else", () => {
    const yml = readFileSync(`${repo}/.github/workflows/loop.yml`, "utf8");
    expect(yml, "a pull that could decide would dismiss insights for the whole workspace").not.toMatch(
      /loop\.mjs (decide|push|mine|propose)/,
    );
    expect(yml).toContain("scripts/loop.mjs pull");
    expect(yml, "Loop is off in a fresh CLI until it is enabled; the 29 Sep to 1 Oct nightlies all died on this").toMatch(
      /stitch enable loop \|\| stitch yolo --enable loop[\s\S]*scripts\/loop\.mjs pull/,
    );
    expect(yml, "an unconfigured repository skips; it does not fail").toContain("enabled=false");
    expect(yml).toContain("secrets.LOOP_API_KEY");
    expect(yml, "the Linux build reads STITCH_API_KEY, not LOOP_API_KEY: the 1 Oct run failed 'Missing authentication' with the secret set").toMatch(
      /STITCH_API_KEY: \$\{\{ secrets\.LOOP_API_KEY \}\}/,
    );
    expect(yml).toContain("secrets.STITCH_INSTALLER_URL");
    expect(yml, "the Loop key goes to Loop's host, not the Canvas API the Linux build defaults to").toContain(
      "STITCH_BASE_URL: https://jules.googleapis.com/v2alpha",
    );
    expect(yml, "the merge is checked on the branch, not trusted").toMatch(/render --check[\s\S]*vitest run/);
  });
});

function readdirSyncSafe(p: string): string[] | null {
  try {
    return readdirSync(p);
  } catch {
    return null;
  }
}
