import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repo = fileURLToPath(new URL("..", import.meta.url));

/**
 * Loop's findings are files, and `docs/LOOP.md` and the roadmap's Loop counts
 * are views of them — the same arrangement as the roadmap itself, and it needs
 * the same guard, or the view is the first thing to fall behind.
 */
describe("the Loop findings are derived, not written", () => {
  it("is current — run `node scripts/loop.mjs render`", () => {
    const out = execFileSync("node", [`${repo}/scripts/loop.mjs`, "render", "--check"], {
      cwd: repo,
      encoding: "utf8",
      timeout: 60_000,
    });
    expect(out).toContain("is current");
  }, 120_000);

  it("says it is generated, in the file itself, and where to edit instead", () => {
    const page = readFileSync(`${repo}/docs/LOOP.md`, "utf8");
    expect(page.startsWith("<!-- Generated by scripts/loop.mjs")).toBe(true);
    expect(page).toContain("edit the finding in docs/loop/");
  });

  it("pins the workspace the findings came from", () => {
    const cfg = JSON.parse(readFileSync(`${repo}/.stitch.json`, "utf8"));
    expect(cfg.workspace, "the scripts refuse to guess a workspace").toMatch(/^[0-9a-f-]{36}$/);
  });

  it("puts every finding's project on the roadmap, or says it is new", () => {
    /* A finding that names a project directory that is not there is pointing at
       nothing, and `findingProblems` says so in `render --check`. This reads the
       other half: that the roadmap actually prints the counts. */
    const roadmap = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    const dir = path.join(repo, "docs/loop");
    const any = existsSync(dir) && readdirSync(dir).some((n) => n.endsWith(".md"));
    if (any) expect(roadmap).toContain("[Loop findings](LOOP.md)");
  });

  it("never sends a decision it was not asked to — decide is not what a pull calls", () => {
    /* `decide` pushes to a workspace other people read. The script's pull and
       propose paths must not reach it; this holds the line in the source, where
       an edit would cross it. */
    const script = readFileSync(`${repo}/scripts/loop.mjs`, "utf8");
    const pull = script.slice(script.indexOf('case "pull"'), script.indexOf('case "list"'));
    const propose = script.slice(script.indexOf('case "propose"'), script.indexOf('case "decide"'));
    for (const body of [pull, propose]) {
      expect(body, "these two commands only read Loop and write files").not.toMatch(/await push\(|upsertContext|stitch\(\[\s*"(dismiss|create|delete|edit)"/);
    }
  });
});
