import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repo = fileURLToPath(new URL("..", import.meta.url));
const script = readFileSync(fileURLToPath(new URL("../scripts/roadmap.mjs", import.meta.url)), "utf8");

/**
 * `docs/ROADMAP.md` is a VIEW. The thing it is a view of is the front matter
 * of each document, which sits beside the words it describes and therefore
 * cannot drift from them — unlike the hand-kept copy it replaces, which on
 * 29 Aug let one research note carry two contradictory verdicts dated the same
 * day.
 */
describe("the roadmap is derived, not written", () => {
  it("is current — run `node scripts/roadmap.mjs`", () => {
    // The whole arrangement is worth nothing if the generated file is allowed
    // to fall behind the front matter it comes from, which is the same staleness
    // one level along.
    const out = execFileSync("node", [`${repo}/scripts/roadmap.mjs`, "--check"], {
      cwd: repo,
      encoding: "utf8",
      timeout: 60_000,
    });
    expect(out).toContain("is current");
  }, 120_000);

  it("says it is generated, in the file itself", () => {
    const page = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    expect(page.startsWith("<!-- Generated by scripts/roadmap.mjs")).toBe(true);
    expect(page, "and where to edit instead").toContain("edit the front matter");
  });

  it("reads front matter through core, not with a parser of its own", () => {
    /**
     * A second little parser here is exactly how the roadmap would come to
     * disagree with the docs it summarises — the bug it exists to fix, rebuilt
     * inside the fix.
     *
     * This used to assert the SPAWN — that the script shelled out to `isocan
     * doc status`. That was the mechanism, not the invariant, and it cost 62
     * CLI spawns a run (~35s) to satisfy. The invariant is that core's
     * `docStatus` is the one reader; the script now imports it directly, which
     * is the same reader and 80x cheaper.
     */
    expect(script).toMatch(/docStatus[^\n]*await import\("@isocan\/core"\)|docStatus.*from "@isocan\/core"/s);
    expect(script).not.toContain("splitFrontMatter");
    expect(script).not.toMatch(/\/\^---\\n/);
  });

  it("agrees with `isocan doc status` about a document", () => {
    /**
     * The textual guard above can only say the script *mentions* the right
     * reader. This says the two surfaces answer the same thing about the same
     * file — the property "one reader" exists to buy — through the CLI, which
     * is the other way a person asks.
     *
     * One spawn, not one per document: the script reaching `docStatus` in
     * process is what made the 62 affordable to drop.
     */
    const page = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    // The heading→state map read out of the script rather than restated here:
    // a second copy of it is a second thing to keep in step, which is the
    // failure mode the roadmap itself exists to end.
    const labels = /const LABEL = \{([^}]*)\}/.exec(script);
    expect(labels, "scripts/roadmap.mjs no longer declares LABEL").not.toBeNull();
    const state: Record<string, string> = {};
    for (const [, key, label] of labels![1].matchAll(/(\w+): "([^"]*)"/g)) state[label] = key;
    let section = "";
    let checked = 0;
    for (const line of page.split("\n")) {
      const head = /^## (.+?) <sub>/.exec(line);
      if (head) {
        section = state[head[1]] ?? "";
        continue;
      }
      const row = /^\| (?:\*\*project\*\*|research) \| \[[^\]]*\]\(([^)]+)\)/.exec(line);
      if (!row || checked >= 2) continue;
      checked += 1;
      const answer = JSON.parse(
        execFileSync("node", [`${repo}/packages/cli/bin/isocan.js`, "--json", "doc", "status", path.join(repo, "docs", row[1])], {
          cwd: repo,
          encoding: "utf8",
          timeout: 60_000,
        }),
      );
      expect(answer.status, `${row[1]} is under "${section}" in the roadmap`).toBe(section);
    }
    expect(checked, "the roadmap had no rows to check").toBeGreaterThan(0);
  }, 120_000);

  it("counts the untriaged out loud", () => {
    // An untriaged doc is not a doc nobody needs; it is a doc nobody has read
    // lately, and hiding that number would make the roadmap flattering.
    const page = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    expect(page).toContain("no verdict recorded at all");
  });

  it("links every row to a file that exists, read from where the page lives", () => {
    /**
     * Every row linked `docs/research/…` from inside `docs/`, so all 79 went to
     * `docs/docs/…` from the day the generator was written until #232 (Paul
     * Kinlan, 11 Sep 2026). The test above checks two rows through the CLI,
     * which is about agreeing on a status; this checks every row's link, which
     * is about arriving — a link that reads as real and goes nowhere is the
     * same failure as a stale verdict.
     */
    const page = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    const links = [...page.matchAll(/^\| (?:\*\*project\*\*|research) \| \[[^\]]*\]\(([^)]+)\)/gm)].map((m) => m[1]!);
    expect(links.length, "the roadmap had no rows to check").toBeGreaterThan(0);
    const missing = links.filter((rel) => !existsSync(path.join(repo, "docs", rel)));
    expect(missing, "a roadmap row whose link does not resolve from docs/").toEqual([]);
  });
});
