import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repo = fileURLToPath(new URL("..", import.meta.url));
const script = readFileSync(fileURLToPath(new URL("../scripts/roadmap.mjs", import.meta.url)), "utf8");

/**
 * `docs/ROADMAP.md` is a VIEW. The thing it is a view of is the front matter
 * of each document, which sits beside the words it describes and therefore
 * cannot drift from them — unlike the hand-kept copy it replaces, which on
 * 29 Aug let one research note carry two contradictory verdicts dated the same
 * day.
 */
describe("the roadmap is derived, not written", () => {
  it("is current — run `node scripts/roadmap.mjs`", () => {
    // The whole arrangement is worth nothing if the generated file is allowed
    // to fall behind the front matter it comes from, which is the same staleness
    // one level along.
    const out = execFileSync("node", [`${repo}/scripts/roadmap.mjs`, "--check"], {
      cwd: repo,
      encoding: "utf8",
      timeout: 60_000,
    });
    expect(out).toContain("is current");
  }, 120_000);

  it("says it is generated, in the file itself", () => {
    const page = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    expect(page.startsWith("<!-- Generated by scripts/roadmap.mjs")).toBe(true);
    expect(page, "and where to edit instead").toContain("edit the front matter");
  });

  it("reads front matter through core, not with a parser of its own", () => {
    /**
     * A second little parser here is exactly how the roadmap would come to
     * disagree with the docs it summarises — the bug it exists to fix, rebuilt
     * inside the fix.
     *
     * This used to assert the SPAWN — that the script shelled out to `isocan
     * doc status`. That was the mechanism, not the invariant, and it cost 62
     * CLI spawns a run (~35s) to satisfy. The invariant is that core's
     * `docStatus` is the one reader; the script now imports it directly, which
     * is the same reader and 80x cheaper.
     */
    expect(script).toMatch(/docStatus[^\n]*await import\("@isocan\/core"\)|docStatus.*from "@isocan\/core"/s);
    expect(script).not.toContain("splitFrontMatter");
    expect(script).not.toMatch(/\/\^---\\n/);
  });

  it("agrees with `isocan doc status` about a document", () => {
    /**
     * The textual guard above can only say the script *mentions* the right
     * reader. This says the two surfaces answer the same thing about the same
     * file — the property "one reader" exists to buy — through the CLI, which
     * is the other way a person asks.
     *
     * One spawn, not one per document: the script reaching `docStatus` in
     * process is what made the 62 affordable to drop.
     */
    const page = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    // The heading→state map read out of the script rather than restated here:
    // a second copy of it is a second thing to keep in step, which is the
    // failure mode the roadmap itself exists to end.
    const labels = /const LABEL = \{([^}]*)\}/.exec(script);
    expect(labels, "scripts/roadmap.mjs no longer declares LABEL").not.toBeNull();
    const state: Record<string, string> = {};
    for (const [, key, label] of labels![1]!.matchAll(/(\w+): "([^"]*)"/g)) state[label!] = key!;
    let section = "";
    let checked = 0;
    for (const line of page.split("\n")) {
      const head = /^## (.+?) <sub>/.exec(line);
      if (head) {
        section = state[head[1]!] ?? "";
        continue;
      }
      const row = /^\| (?:\*\*project\*\*|research) \| \[[^\]]*\]\(([^)]+)\)/.exec(line);
      if (!row || checked >= 2) continue;
      checked += 1;
      const answer = JSON.parse(
        execFileSync("node", [`${repo}/packages/cli/bin/isocan.js`, "--json", "doc", "status", path.join(repo, "docs", row[1]!)], {
          cwd: repo,
          encoding: "utf8",
          timeout: 60_000,
        }),
      );
      expect(answer.status, `${row[1]} is under "${section}" in the roadmap`).toBe(section);
    }
    expect(checked, "the roadmap had no rows to check").toBeGreaterThan(0);
  }, 120_000);

  it("counts the untriaged out loud", () => {
    // An untriaged doc is not a doc nobody needs; it is a doc nobody has read
    // lately, and hiding that number would make the roadmap flattering.
    const page = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    expect(page).toContain("no verdict recorded at all");
  });

  it("links every row to a file that exists, read from where the page lives", () => {
    /**
     * Every row linked `docs/research/…` from inside `docs/`, so all 79 went to
     * `docs/docs/…` from the day the generator was written until #232 (Paul
     * Kinlan, 11 Sep 2026). The test above checks two rows through the CLI,
     * which is about agreeing on a status; this checks every row's link, which
     * is about arriving — a link that reads as real and goes nowhere is the
     * same failure as a stale verdict.
     */
    const page = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    const links = [...page.matchAll(/^\| (?:\*\*project\*\*|research) \| \[[^\]]*\]\(([^)]+)\)/gm)].map((m) => m[1]!);
    expect(links.length, "the roadmap had no rows to check").toBeGreaterThan(0);
    const missing = links.filter((rel) => !existsSync(path.join(repo, "docs", rel)));
    expect(missing, "a roadmap row whose link does not resolve from docs/").toEqual([]);
  });

  it("opens with what needs a person, every walk linked to a file that exists", () => {
    /**
     * The one list on the roadmap no commit can shorten. It comes first because
     * "what do we need people to test?" had no answer anywhere a reader looked
     * first — the queue lived in `docs/verify/README.md` and nowhere else.
     */
    const page = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    const first = /^## (.+?) <sub>/m.exec(page);
    expect(first?.[1]).toBe("What needs a person");
    const links = [...page.matchAll(/^\| \*\*(?:unverified|broken)\*\* \| \[[^\]]*\]\(([^)]+)\)/gm)].map((m) => m[1]!);
    const missing = links.filter((rel) => !existsSync(path.join(repo, "docs", rel)));
    expect(missing, "a walk row whose link does not resolve from docs/").toEqual([]);
  });

  it("a publish leaves the file alone — it runs detached, where a rewrite could stop a rebase", () => {
    const before = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    execFileSync("node", [`${repo}/scripts/roadmap.mjs`, "--publish", "--dry-run"], { cwd: repo, encoding: "utf8", timeout: 60_000 });
    expect(readFileSync(`${repo}/docs/ROADMAP.md`, "utf8")).toBe(before);
    expect(script).toMatch(/if \(!process\.argv\.includes\("--publish"\)\) \{\n\s*writeFileSync\(out, page\)/);
  }, 120_000);

  it("publishes the canvas card only when asked, with links that resolve off the repo", () => {
    /**
     * The canvas copy was hand-kept and drifted (7 Oct 2026); now it is this
     * page, published. On a canvas there is no `docs/` for a relative link to
     * resolve from, so every one is rewritten to GitHub, and the card says
     * which commit it came from.
     */
    expect(script).toMatch(/if \(process\.argv\.includes\("--publish"\)\) \{\n[^]*?await publishToCanvas\(page\)\.catch/);
    // --check exits before the publish line can run.
    expect(script.indexOf('includes("--check")')).toBeLessThan(script.indexOf("await publishToCanvas(page)"));
    const said = execFileSync("node", [`${repo}/scripts/roadmap.mjs`, "--publish", "--dry-run"], { cwd: repo, encoding: "utf8", timeout: 60_000 });
    const file = /would publish "Roadmap" → (.+)$/m.exec(said)?.[1];
    expect(file, said).toBeTruthy();
    const card = readFileSync(file!.trim(), "utf8");
    expect(card).toMatch(/^> Generated from `main` at \[`[0-9a-f]+`\]/);
    expect(card).not.toMatch(/\]\((projects|research|verify|loop)\//);
    expect(card).toContain("](https://github.com/dglazkov/isocan/blob/main/docs/");
  }, 120_000);

  it("cannot make anything red: a failing publish leaves the commit hook at exit 0, and says so in its log", () => {
    // Run the real hook in a scratch repo whose roadmap.mjs fails the way an
    // unreachable home would. The commit must not hear about it.
    const dir = mkdtempSync(path.join(os.tmpdir(), "acme-roadmap-hook-"));
    try {
      const git = (...a: string[]) => execFileSync("git", a, { cwd: dir, encoding: "utf8", timeout: 30_000, env: { ...process.env, GIT_CONFIG_GLOBAL: "/dev/null" } });
      git("init", "-q");
      mkdirSync(path.join(dir, "scripts"), { recursive: true });
      mkdirSync(path.join(dir, ".isocan"), { recursive: true });
      writeFileSync(path.join(dir, "scripts", "roadmap.mjs"), 'console.error("home unreachable"); process.exit(1);\n');
      writeFileSync(path.join(dir, ".isocan", "roadmap.json"), '{"canvas":"prj_ACME"}');
      const hook = path.join(repo, "scripts", "hooks", "post-commit");
      const out = execFileSync("sh", [hook], { cwd: dir, encoding: "utf8", timeout: 30_000 });
      expect(out).toContain("roadmap.log");
      // The publish is detached; wait for its log line rather than a count of ticks.
      const log = path.join(dir, ".isocan", "roadmap.log");
      const until = Date.now() + 20_000;
      while (Date.now() < until && !(existsSync(log) && /exit \d/.test(readFileSync(log, "utf8")))) execFileSync("sleep", ["0.1"], { timeout: 5_000 });
      expect(readFileSync(log, "utf8")).toMatch(/home unreachable[\s\S]*exit 1/);
      // And never mid-rebase, when every replayed commit runs this hook.
      mkdirSync(path.join(dir, ".git", "rebase-merge"));
      const during = execFileSync("sh", [hook], { cwd: dir, encoding: "utf8", timeout: 30_000 });
      expect(during).not.toContain("roadmap.log");
    } finally {
      rmSync(dir, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
    }
  }, 60_000);
});
