import { describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const repo = fileURLToPath(new URL("..", import.meta.url));
const script = readFileSync(fileURLToPath(new URL("../scripts/roadmap.mjs", import.meta.url)), "utf8");

/**
 * `docs/ROADMAP.md` is a VIEW. The thing it is a view of is the front matter
 * of each document, which sits beside the words it describes and therefore
 * cannot drift from them — unlike the hand-kept copy it replaces, which on
 * 29 Aug let one research note carry two contradictory verdicts dated the same
 * day.
 */
describe("the roadmap is derived, not written", () => {
  it("is current — run `node scripts/roadmap.mjs`", () => {
    // The whole arrangement is worth nothing if the generated file is allowed
    // to fall behind the front matter it comes from, which is the same staleness
    // one level along.
    const out = execFileSync("node", [`${repo}/scripts/roadmap.mjs`, "--check"], {
      cwd: repo,
      encoding: "utf8",
      timeout: 60_000,
    });
    expect(out).toContain("is current");
  }, 120_000);

  it("says it is generated, in the file itself", () => {
    const page = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    expect(page.startsWith("<!-- Generated by scripts/roadmap.mjs")).toBe(true);
    expect(page, "and where to edit instead").toContain("edit the front matter");
  });

  it("reads front matter through core, not with a parser of its own", () => {
    /**
     * A second little parser here is exactly how the roadmap would come to
     * disagree with the docs it summarises — the bug it exists to fix, rebuilt
     * inside the fix.
     */
    expect(script).toContain("doc\", \"status\"");
    expect(script).not.toContain("splitFrontMatter");
    expect(script).not.toMatch(/\/\^---\\n/);
  });

  it("counts the untriaged out loud", () => {
    // An untriaged doc is not a doc nobody needs; it is a doc nobody has read
    // lately, and hiding that number would make the roadmap flattering.
    const page = readFileSync(`${repo}/docs/ROADMAP.md`, "utf8");
    expect(page).toContain("no verdict recorded at all");
  });
});
