import { useEffect, useState } from "react";
import type { Actor, DesignArtifactRef } from "@isocan/core";
import { newItemId, newVersionId } from "@isocan/core";
import { parseDesignReceipt } from "@isocan/core/design-partner";
import type { DesignReceiptView as ReceiptView, DesignRequestView } from "@isocan/api/design-request";
import { useCanvasStore } from "../stores/canvasStore.ts";
import { useDesignMutation } from "../lib/design-request-draft.ts";
import { emptyDesignCheck, readDesignReceiptDraft, receiptDraftChangedItems, receiptFromDraft, type DesignCheckDraft as CheckDraft, type DesignReceiptDraft as ReceiptDraft } from "../lib/design-receipt-draft.ts";
import { MutationNotice } from "./DesignTaskPanel.tsx";
import { RequestReferenceCard } from "./RequestReferenceCard.tsx";

/** Published checks are attributed reports; freshness never changes the historical result of a check. */
export function DesignReceiptView({ canvasId, requestId, saved, checking = false }: { canvasId: string; requestId: string; saved: ReceiptView; checking?: boolean }) {
  const { receipt } = saved;
  return <section className="design-receipt" data-design-receipt={receipt.id}>
    <h4>{checking ? "Checking evidence…" : saved.status === "stale" ? "Evidence needs refreshing" : saved.status === "unavailable" ? "Evidence unavailable" : receipt.status === "ready" ? "Ready for the agreed scope" : "Unverified draft"}</h4>
    <small>Reported by {saved.author.name} · {receipt.fidelity}</small>
    {receipt.output.kind === "repository" && <p>Connected runtime: <a href={receipt.output.runtimeUrl} target="_blank" rel="noopener noreferrer">Open application</a><br /><small>Build freshness is a reported observation.</small></p>}
    {saved.reasons.map((reason) => <p key={reason} role="status">{reason}</p>)}
    {receipt.checks.map((check) => <div key={check.id} className="design-receipt-check"><strong>{check.kind === "source" ? "Source check" : check.kind === "browser-task" ? "Browser / task check" : "Craft review"} · {check.result}</strong><p>{check.coverage}</p>{saved.checkFreshness.find((one) => one.checkId === check.id)?.status !== "current" && <p role="status">This check’s evidence is {saved.checkFreshness.find((one) => one.checkId === check.id)?.status ?? "unavailable"}.</p>}<small>{check.state}{check.viewport ? ` · ${check.viewport.width} × ${check.viewport.height}` : ""}</small></div>)}
    {receipt.unresolved.length > 0 && <div><strong>Remaining limits</strong><ul>{receipt.unresolved.map((limit, index) => <li key={index}>{limit.description}{limit.severity === "critical" ? " · critical" : ""}</li>)}</ul></div>}
    <details><summary>Checks, tools and exact evidence</summary>{receipt.checks.map((check) => <section key={check.id}><p>{check.tool} · {check.toolVersion}</p>{check.evidence.map((artifact) => <RequestReferenceCard key={JSON.stringify(artifact)} canvasId={canvasId} requestId={requestId} artifact={artifact} />)}</section>)}{receipt.output.kind === "canvas" ? <RequestReferenceCard canvasId={canvasId} requestId={requestId} artifact={receipt.output.artifact} /> : <p>Repository {receipt.output.repository}<br />Revision {receipt.output.revision}<br />Build {receipt.output.buildId}</p>}<p>Receipt {receipt.id} · brief {receipt.brief.versionId}</p></details>
  </section>;
}

/** Completion evidence has an output and named checks; an empty checkbox can never stand for verification. */
export function DesignReceiptEditor({ canvasId, actor, row, checking = false, done }: { canvasId: string; actor: Actor; row: DesignRequestView; checking?: boolean; done: () => void }) {
  const canvas = useCanvasStore((state) => state.canvas);
  const key = `isocan.design.receipt.v2:${JSON.stringify([canvasId, actor.id, row.brief.requestId])}`;
  const artifact = (id: string): DesignArtifactRef | null => { const item = canvas?.items[id]; const version = item?.versions.find((one) => one.id === item.currentVersionId); return version ? { home: row.ref.home, canvasId, itemId: id, versionId: version.id, blobHash: version.blobHash } : null; };
  const capture = (outputId: string): Pick<ReceiptDraft, "brief" | "epoch" | "fidelity" | "delivery" | "context" | "governing" | "output"> => ({ brief: row.ref, epoch: row.brief.epoch, fidelity: row.brief.fidelity, delivery: row.brief.delivery, context: row.contextReferences, governing: row.brief.delivery === "connected-app" ? row.governingBinding : row.outputGovernings.find((one) => one.itemId === outputId && one.governing.status !== "unavailable")?.binding ?? null, output: artifact(outputId) });
  const [restored] = useState(() => { try { const raw = localStorage.getItem(key); return { draft: readDesignReceiptDraft(raw), corrupt: !!raw && !readDesignReceiptDraft(raw) }; } catch { return { draft: null, corrupt: true }; } });
  const [recoveryRequired, setRecoveryRequired] = useState(restored.corrupt);
  const [draft, setDraft] = useState<ReceiptDraft>(() => restored.draft ?? { schemaVersion: 2, ...capture(row.brief.outputIds[0] ?? ""), repository: "", revision: "", buildId: "", runtimeUrl: "", status: "draft", limits: "", critical: false, checks: [emptyDesignCheck()] });
  const [error, setError] = useState("");
  const [storageError, setStorageError] = useState("");
  const mutation = useDesignMutation(canvasId, actor, `receipt:${row.brief.requestId}`, () => { try { localStorage.removeItem(key); } catch { /* Accepted evidence is already durable. */ } done(); });
  useEffect(() => { if (recoveryRequired) return; try { localStorage.setItem(key, JSON.stringify(draft)); setStorageError(""); } catch { setStorageError("Evidence details could not be saved for refresh. Keep this page open."); } }, [key, draft, recoveryRequired]);
  const items = Object.values(canvas?.items ?? {}).filter((item) => !item.versions.find((version) => version.id === item.currentVersionId)?.designRecord);
  const patch = (value: Partial<ReceiptDraft>) => setDraft((old) => ({ ...old, ...value }));
  const patchCheck = (id: string, value: Partial<CheckDraft>) => patch({ checks: draft.checks.map((check) => check.id === id ? { ...check, ...value } : check) });
  const changedItems = receiptDraftChangedItems(draft, canvas, canvasId);
  const currentBinding = draft.delivery === "connected-app" ? row.governingBinding : row.outputGovernings.find((one) => one.itemId === draft.output?.itemId)?.binding ?? null;
  const stale = row.status !== "current" || !row.allowedActions.includes("receipt") || changedItems.length > 0 || JSON.stringify(draft.brief) !== JSON.stringify(row.ref) || JSON.stringify(draft.context) !== JSON.stringify(row.contextReferences) || JSON.stringify(draft.governing) !== JSON.stringify(currentBinding);
  const refreshTargets = (outputId = draft.output?.itemId ?? "") => patch({ ...capture(outputId), status: "draft", checks: [emptyDesignCheck()] });
  async function publish() {
    setError("");
    try {
      if (mutation.pending) { await mutation.run(); return; }
      if (stale || checking) throw new Error("The captured output or context changed. Refresh the targets and check them again before publishing.");
      const receipt = parseDesignReceipt(receiptFromDraft(draft, row.brief.requestId, `receipt_${crypto.randomUUID()}`));
      await mutation.run({ type: "design.receipt", itemId: newItemId(), versionId: newVersionId(), title: "Design task evidence", receipt });
    } catch (cause) { setError(cause instanceof Error ? cause.message : "The evidence details could not be published."); }
  }
  return <form className="design-task-editor" aria-label="Publish design evidence" onSubmit={(event) => { event.preventDefault(); void publish(); }}><h4>Record your own evidence</h4><p>This form publishes a report you have already made; it does not run checks. For the agent’s ongoing review, open Review and checks. Changing the output or runtime identity resets the checks recorded here.</p>
    {recoveryRequired && <p role="alert">An earlier evidence draft could not be read. Its saved contents have been preserved. <button type="button" className="btn secondary" onClick={() => { try { const raw = localStorage.getItem(key); if (raw) localStorage.setItem(`${key}:recovery:${Date.now()}`, raw); setRecoveryRequired(false); } catch { setStorageError("The unreadable draft could not be preserved. Free browser storage before starting again."); } }}>Preserve old draft and start again</button></p>}{stale && <p role="alert">The output, evidence or task context changed after this draft began. The earlier checks still name their original versions. <button type="button" className="btn secondary" disabled={checking || !!mutation.pending} onClick={() => refreshTargets()}>Refresh targets and reset checks</button></p>}
    <fieldset disabled={mutation.busy || !!mutation.pending || stale || checking || recoveryRequired}>{row.brief.delivery === "connected-app" ? <>{([['repository', 'Repository'], ['revision', 'Revision'], ['buildId', 'Build identity'], ['runtimeUrl', 'Running application URL']] as const).map(([field, title]) => <label key={field}>{title}<input required type={field === "runtimeUrl" ? "url" : "text"} value={draft[field]} onChange={(event) => patch({ [field]: event.target.value, status: "draft", checks: [emptyDesignCheck()] })} /></label>)}</> : <label>Checked output<select required value={draft.output?.itemId ?? ""} onChange={(event) => refreshTargets(event.target.value)}><option value="">Choose an output…</option>{items.filter((item) => row.brief.outputIds.includes(item.id)).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label>}
      {draft.checks.map((check, index) => <details key={check.id} open={check.result !== "unavailable"}><summary>Check {index + 1} · {check.result === "unavailable" ? "Browser unavailable — draft only" : check.coverage || "Describe the check"}</summary><label>Check kind<select value={check.kind} onChange={(event) => patchCheck(check.id, { kind: event.target.value as CheckDraft["kind"] })}><option value="browser-task">Browser / task</option><option value="source">Source diagnostics</option><option value="craft">Craft review</option></select></label><label>Observed result<select value={check.result} onChange={(event) => patchCheck(check.id, { result: event.target.value as CheckDraft["result"] })}><option value="unavailable">Could not check</option><option value="passed">Passed the named check</option><option value="failed">Failed the named check</option></select></label>{([['coverage', 'What was checked'], ['state', 'State exercised'], ['tool', 'Tool'], ['toolVersion', 'Tool version'], ['width', 'Viewport width'], ['height', 'Viewport height']] as const).map(([field, title]) => <label key={field}>{title}<input value={check[field]} onChange={(event) => patchCheck(check.id, { [field]: event.target.value })} /></label>)}<label>Evidence items<select multiple value={check.evidence.map((ref) => ref.itemId)} onChange={(event) => patchCheck(check.id, { evidence: Array.from(event.target.selectedOptions, (option) => { const ref = check.evidence.find((one) => one.itemId === option.value) ?? artifact(option.value); if (!ref) throw new Error("This evidence is no longer available."); return ref; }) })}>{items.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label></details>)}
      {draft.checks.length < 32 && <button type="button" className="btn secondary" onClick={() => patch({ checks: [...draft.checks, { ...emptyDesignCheck(), coverage: "", state: "", tool: "", toolVersion: "" }] })}>Add check</button>}
      <label>Remaining limits, one per line<textarea rows={2} value={draft.limits} onChange={(event) => patch({ limits: event.target.value })} /></label><label className="design-task-inline"><input type="checkbox" checked={draft.critical} onChange={(event) => patch({ critical: event.target.checked })} />These limits block the primary task</label><label>Delivery claim<select value={draft.status} onChange={(event) => patch({ status: event.target.value as ReceiptDraft["status"] })}><option value="draft">Draft — verification incomplete</option><option value="ready">Ready for the agreed scope</option></select></label>
    </fieldset>{error && <p role="alert">{error}</p>}{storageError && <p role="alert">{storageError}</p>}<MutationNotice mutation={mutation} /><footer><button type="button" className="btn secondary" onClick={done}>Close</button><button className="btn primary" disabled={mutation.busy || !mutation.pending && (stale || checking || recoveryRequired || !draft.governing)}>{mutation.pending ? "Retry evidence publication" : "Publish receipt"}</button></footer>
  </form>;
}
