import { questionnaireFixture } from "./questionnaire-fixture.ts";
import type { DesignComparison, DesignDecisionInput } from "@isocan/core/design-decision";
import { prepareDesignDecision, type DesignComparisonView } from "@isocan/api";

/** Real synthetic admitted work shared by API and CLI decision tests; no model or external service is invoked. */
export async function designDecisionFixture(options: { external?: boolean; existing?: boolean } = {}) {
  const f = await questionnaireFixture();
  try {
    const target = options.existing ? await f.agentCanvas.add({ title: "Acme receiving", content: "<main>Current receiving task</main>", mime: "text/html", filename: "receiving.html", description: "Existing receiving screen" }) : null;
    const alternatives = await Promise.all(["continuous", "each"].map(name => f.agentCanvas.add({ title: name === "continuous" ? "Continuous receipt" : "Confirm each line", content: `<main><h1>Acme delivery</h1><p>Three stock lines, quantities 4, 2 and 1.</p><button>${name === "continuous" ? "Review receipt" : "Confirm line"}</button></main>`, mime: "text/html", filename: `${name}.html` })));
    const requestId = "req_acme_decision";
    const started = await f.agentCanvas.designStart({ opId: "op_acme_decision_start", action: { kind: "start", requestId, itemId: "itm_acme_decision_brief", versionId: "ver_acme_decision_brief", admission: "explicit", source: options.external ? { entrance: "external-agent", externalRequestId: "native_acme_receiving" } : { entrance: "canvas-chat", threadId: f.original.threadId, commentId: f.original.commentId }, fields: { intent: options.existing ? "refine" : "create", fidelity: "wireframe", delivery: "html-node", targetItemId: target?.id ?? null, groupId: null, audience: "Receiving staff", primaryTask: "Receive three stock lines", constraints: [], facts: [], references: [], outstandingDecisionIds: ["workflow"], outputIds: [] } } });
    if (started.status !== "accepted") throw new Error(`Synthetic request start failed: ${JSON.stringify(started)}`);
    const request = (await f.client.designRequests(f.canvasId)).requests.find(one => one.brief.requestId === requestId)!;
    const artifact = (item: typeof alternatives[number]) => ({ home: f.base, canvasId: f.canvasId, itemId: item.id, versionId: item.currentVersionId, blobHash: item.versions.find(one => one.id === item.currentVersionId)!.blobHash });
    const comparison: DesignComparison = { schemaVersion: 1, kind: "comparison", id: "cmp_acme_receiving", revision: 1, requestId, epoch: request.brief.epoch, brief: request.ref, decisionKey: "workflow", audience: options.external ? { kind: "external-agent", externalRequestId: "native_acme_receiving", reporterActorId: f.agent.actor.id } : { kind: "human", respondentActorId: f.person.actor.id }, mode: "comparison", uncertainty: "structure", scenario: "Receive the same three Acme stock lines with quantities 4, 2 and 1.", fidelity: "wireframe", alternatives: alternatives.map((item, index) => ({ id: index ? "each" : "continuous", title: item.title, hypothesis: index ? "Confirming each line catches errors immediately." : "Continuous scanning reduces repeated taps.", tradeoff: index ? "More repeated confirmation." : "Needs a final receipt review.", artifact: artifact(item) })), recommendedAlternativeId: "continuous", recommendation: "Use continuous scanning for this small receiving batch.", target: { itemId: target?.id ?? null, groupId: null }, governing: { atItemId: target?.id ?? null, artifact: null, explicitNone: false }, supersedes: null, correctsDecisionId: null, followsResponseId: null };
    const publication = { canvasId: f.canvasId, threadId: f.original.threadId, commentId: "cmt_acme_comparison", opId: "op_acme_comparison", comparison };
    const decide = (view: DesignComparisonView, authority: DesignDecisionInput["authority"] = { kind: "human-choice", reason: null }) => prepareDesignDecision({ canvasId: f.canvasId, threadId: view.source.threadId, commentId: "cmt_acme_decision", opId: "op_acme_decision", decision: { id: "decision_acme_receiving", requestId, decisionKey: "workflow", source: { kind: "comparison", source: view.source }, basis: view.approvalBases.find(one => one.alternativeId === "continuous")!.basis!, chosenAlternativeId: "continuous", versionId: "ver_acme_adopted", supersedesDecisionId: null, authority } });
    return { ...f, request, target, alternatives, artifact, comparison, publication, decide };
  } catch (error) { await f.close(); throw error; }
}
