import { promises as fs } from "node:fs";
import path from "node:path";
import type { Command } from "commander";
import type { Actor, MetaPatch, Project } from "@isocan/core";
import { DEFAULT_PORT, newProjectId } from "@isocan/core";
import { paths, readConfigFile, stalenessOf, type HomeConfig } from "@isocan/server";
import { ApiError, DaemonClient, type Health } from "./client.ts";
import { requireIdentity, resolveIdentity, retireStrandedIdentities } from "./identity.ts";
import type { HarnessVarConfig } from "./harness.ts";
import {
  bindableRoot,
  findBinding,
  markerFile,
  recordDir,
  writeMarker,
  type DirBinding,
} from "./binding.ts";

export interface Ctx {
  client: DaemonClient;
  actor: Actor;
  json: boolean;
  home: string;
  projectRef?: string;
  /** The directory's canvas, when the cwd sits under a `.isocan/project.json`
   * marker (#60). Resolved once per command; null outside any bound tree. */
  binding: DirBinding | null;
  /**
   * **Where a canvas born here, naming nothing, would be born** — and nothing
   * else.
   *
   * Read once per command off the health route rather than from this machine's
   * own config, deliberately: what matters is what the daemon ACTUALLY is — a
   * CLI whose config was edited five minutes ago and a daemon that has been
   * running since Tuesday must not disagree about where a canvas goes.
   *
   * **It was called `homeUrl` and it was renamed on purpose** (phase 10.3).
   * The old name invited exactly one mistake: using a daemon-wide value to
   * build A SPECIFIC CANVAS's address. On a machine with two homes that prints
   * `dev.isocan.io/p/<a canvas that lives on this laptop>` — the cheerful
   * wrong address, generated by us, in the one string a person pastes to
   * another person. The rename made the typechecker walk every reader so each
   * one could be decided rather than assumed, and the readers that wanted a
   * canvas's home now say so: {@link Ctx.homeOf}.
   */
  birthHome: string | null;
  /**
   * **Where THIS canvas lives** — the address to build its page URL from, or
   * null when this daemon is its home (so the caller's own base is the one
   * origin for it).
   *
   * Off `GET /api/homes`, fetched at most once per command and only when
   * somebody asks: a read that prints no address needs no round trip.
   */
  homeOf(projectId: string): Promise<string | null>;
  /** The whole record, for the two callers that need more than one canvas's
   * answer — `isocan status`'s role line and the refusal below. */
  homes(): Promise<HomeRecord>;
}

/**
 * **What this machine has recorded about where its canvases live** — `GET
 * /api/homes`, plus the one thing the route cannot say about itself.
 *
 * The three-state answer is the whole reason this is not a plain map. For one
 * canvas id there are three different facts, and phase 10.3's refusals turn on
 * telling them apart:
 *
 * - **a row naming an address** — this machine has been to that home for this
 *   canvas and wrote it down;
 * - **a row naming `null`** — this daemon IS its home, recorded at birth
 *   (deliberately explicit: it is what stops a link's sweep later claiming a
 *   locally-born canvas under "no row, so adopt it");
 * - **no row at all** — this machine has never had anything to do with this
 *   canvas. That is the cloned-marker case, and it must JOIN rather than
 *   refuse.
 */
export interface HomeRecord {
  /** Where a canvas born here, naming nothing, goes. */
  birth: string | null;
  /** Every home this daemon dials, and whether its last poll was answered. */
  links: { url: string; reachable: boolean | null }[];
  /** This canvas's row: an address, `null` for "here", `undefined` for "no row
   * — this machine has never recorded anything about that canvas". */
  rowFor(projectId: string): string | null | undefined;
  /** Every row, for the summaries. */
  rows: Record<string, string | null>;
  /**
   * **This daemon predates `GET /api/homes`**, so every answer above is
   * inferred from the health route's one field.
   *
   * Not a hypothetical: a daemon outlives the CLI that started it, which is
   * the entire reason `warnIfStale` exists — an upgraded CLI talking to
   * yesterday's daemon is the ordinary case for a few minutes. On such a
   * daemon there is exactly one home and it is the one the health route names,
   * so treating every canvas as living there is not a guess, it is that
   * daemon's actual model. Getting this wrong the other way would print
   * `127.0.0.1` for canvases that live at a home — the cheerful wrong address
   * again, introduced by an upgrade.
   */
  legacy: boolean;
}

export async function makeCtx(cmd: Command): Promise<Ctx> {
  const opts = cmd.optsWithGlobals() as {
    json?: boolean;
    port?: string;
    project?: string;
  };
  const home = paths.isocanHome();
  const port = opts.port ? Number(opts.port) : Number(process.env.ISOCAN_PORT ?? DEFAULT_PORT);
  const client = new DaemonClient(`http://127.0.0.1:${port}`, home);
  // A person at a keyboard is asked once, up front. Everyone else is asked
  // only if it turns out to matter: looking (`ls`, `project list`, `show`)
  // stamps nothing, and an agent should be able to see where it has landed
  // before it decides what to call itself. The getter is what makes that
  // lazy — reads never touch `actor`, so they never demand one.
  await retireStrandedIdentities(process.cwd(), home);
  const known = await resolveIdentity(client, home);
  const actor = known?.actor ?? (process.stdin.isTTY ? await requireIdentity(client, home) : null);
  await client.ensureDaemon();
  // One health call, two answers. It was already being made for the staleness
  // warning; asking it again for the home address would be a second round trip
  // on every command for a field that travels in the same body.
  const health = await client.healthz().catch(() => null);
  await warnIfStale(health, home);
  const birthHome = health?.home ?? null;
  // Lazily, and at most once: `GET /api/homes` is a second round trip, and
  // most commands never name an address. `ls` should not pay for `share`.
  let record: Promise<HomeRecord> | null = null;
  const homes = () => (record ??= readHomeRecord(client, birthHome));
  // Nothing is claimed here. Mechanism 5 asks the badge to vouch for whoever
  // this command speaks as — but a read stamps nothing and names nobody, and
  // an eager claim on every command would put an actors-log entry behind
  // `ls`. `resolveIdentity` has already told the client HOW to claim; the
  // home asking is what makes it happen, exactly once per badge.
  const binding = await findBinding(process.cwd(), home);
  return {
    client,
    get actor(): Actor {
      if (!actor) {
        throw new Error(
          'no identity yet — `isocan identity --name "Your Name" --session` names this agent',
        );
      }
      return actor;
    },
    json: opts.json ?? false,
    home,
    binding,
    birthHome,
    homes,
    async homeOf(projectId: string): Promise<string | null> {
      return homeAddressOf(await homes(), projectId);
    },
    ...(opts.project !== undefined ? { projectRef: opts.project } : {}),
  };
}

/**
 * The record, read once, with the old daemon's answer standing in when the
 * route is not there — see {@link HomeRecord.legacy}.
 *
 * Exported because `ensureDirBinding` runs outside a `Ctx` (the session
 * handshake builds no context) and must ask the same question the same way. A
 * second spelling of "where does this canvas live" is how the two paths would
 * come to disagree.
 */
export async function readHomeRecord(
  client: DaemonClient,
  birthHome: string | null,
): Promise<HomeRecord> {
  const answer = await client.homes().catch(() => null);
  const rows = answer?.canvases ?? {};
  return {
    birth: answer ? answer.birth : birthHome,
    links: answer?.links ?? [],
    rows,
    legacy: answer === null,
    rowFor: (projectId: string) => rows[projectId],
  };
}

/** Where this canvas's page is served from, or null for "this daemon". The one
 * computation behind every address the CLI prints. */
export function homeAddressOf(record: HomeRecord, projectId: string): string | null {
  if (record.legacy) return record.birth;
  return record.rowFor(projectId) ?? null;
}

/**
 * **The marker and the record disagree about where this canvas lives.** Refuse,
 * naming both, and migrate nothing.
 *
 * It used to compare the marker against the DAEMON — "this canvas lives at X
 * and this daemon answers to Y" — and under one home per daemon that was the
 * only comparison available. Phase 10.3 made the home a property of the canvas,
 * so the question moved: the marker is compared against **this machine's own
 * row for that canvas** (`homes.json`, read through `GET /api/homes`). The
 * rename is how every call site got visited rather than grepped for.
 *
 * The five cases, and which of them is a refusal:
 *
 * - **The marker names no home.** Not a refusal, and never was: "absent means
 *   wherever the daemon reading this lives" is the marker's own sentence, and
 *   every marker written before phase 6 lacks the key. The record decides.
 * - **The marker agrees with the row.** The ordinary case.
 * - **The marker names a home this machine has never recorded anything about.**
 *   *Not a refusal — a JOIN.* This is the case the phase exists for: a repo
 *   cloned onto a second machine, whose `.isocan/project.json` says the canvas
 *   lives at dev. `fetchFromHome` asks the daemon to go and get it, the far
 *   door decides, and the row is written. Nothing else on this machine moves.
 * - **The marker names a home, and this machine's row names a DIFFERENT one.**
 *   Refused. An edited marker, two clones that disagree, a canvas re-homed
 *   somewhere else while this checkout slept.
 * - **The marker names a home, and this machine's row says the canvas is
 *   LOCAL** (or holds it with no row at all — a pre-10.3 canvas). Refused, same
 *   sentence: a canvas materialized here under an id whose marker promises
 *   another home is a twin, and pretending either half is authoritative is how
 *   one of them gets overwritten.
 *
 * Moving a canvas between homes is **re-homing** — a thick replica offering
 * its store to a new home and rewriting the marker (innkeeper.md) — and it is
 * phase 13's. What it moves is the WORK and not the desk: badges, grants,
 * attestations and the claims binding actors to badges all stay behind. That
 * is not a migration a command can perform as a side effect of somebody
 * running `isocan ls` in the wrong directory, so nothing here migrates
 * anything. The two addresses are both printed because the interesting
 * question is always which of them is the surprise.
 */
function refuseHomeDisagreement(
  binding: DirBinding,
  record: HomeRecord,
  /** Does this daemon actually hold that canvas? The one fact `GET /api/homes`
   * cannot supply: a canvas held here since before phase 10.3 has no row, and
   * "no row" would otherwise read as "never heard of it", which is the join
   * case rather than the disagreement. */
  heldHere: boolean,
): void {
  if (binding.home === undefined) return; // an older marker; it names no home
  const row = record.legacy ? record.birth : record.rowFor(binding.projectId);
  // No row and not on this machine: nothing to disagree with. `fetchFromHome`
  // takes it from here, and the home the marker names is the one it asks.
  if (row === undefined && !heldHere) return;
  const recorded = row ?? null;
  if (recorded === binding.home) return;
  const mine = recorded
    ? `this machine has that canvas recorded as living at ${recorded}`
    : "this machine holds that canvas as a LOCAL one (this daemon is its home)";
  throw new Error(
    `this directory's canvas lives at ${binding.home} (${markerFile(binding.root)}), but ` +
      `${mine}. Those cannot both be true, and nothing here will guess: moving a canvas ` +
      "between homes is re-homing, a deliberate act that carries the work and leaves the " +
      "desk behind. Either the marker is stale and belongs corrected in git, or this " +
      `machine's record is (\`isocan home\` shows every canvas and where it lives).`,
  );
}

/**
 * A daemon outlives the command that started it, so an upgrade leaves the old
 * one holding the port — silently, since `ensureDaemon` only starts one when
 * nothing answers. Say so, once per daemon: an agent runs dozens of commands
 * and a line on every one of them is noise, but never saying it at all is how
 * you spend an afternoon debugging yesterday's build.
 */
async function warnIfStale(health: Health | null, home: string): Promise<void> {
  try {
    if (!health) return;
    const { stale, why } = stalenessOf(health);
    if (!stale) return;
    const marker = path.join(home, ".stale-warned");
    const said = await fs.readFile(marker, "utf8").catch(() => "");
    if (said.trim() === health.startedAt) return;
    await fs.writeFile(marker, health.startedAt).catch(() => {});
    console.error(`note: ${why} — \`isocan restart\` to run this one.`);
  } catch {
    // Never let a courtesy check break a command.
  }
}

interface ConfigFile extends HarnessVarConfig, HomeConfig {
  defaultProjectId?: string;
}

/** One reader for `config.json`, in `@isocan/server` — the daemon reads the
 * same file for `home` now, and three hand-rolled `try { JSON.parse }` blocks
 * is three chances to disagree about what a malformed file means. */
export async function readConfig(home: string): Promise<ConfigFile> {
  return readConfigFile<ConfigFile>(home);
}

export async function writeConfig(home: string, config: ConfigFile): Promise<void> {
  await fs.mkdir(home, { recursive: true });
  await fs.writeFile(paths.configFile(home), JSON.stringify(config, null, 2));
}

export interface ResolveOptions {
  /** May this resolution CREATE the directory's project: materialize a
   * marker whose store is missing here (a fresh clone), or bind an unbound
   * directory to a brand-new project. Passed by the commands that can put
   * something onto an empty canvas — and the session handshake — never by
   * reads, so `ls` in a stray directory cannot mint canvases. */
  create?: boolean;
}

/**
 * Which project a command means (#60). In order: --project says so; the
 * directory says so (the nearest `.isocan/project.json` marker, git-style
 * walk-up); the home default (`isocan use --home`), consulted only OUTSIDE
 * bound directories; the only project there is; and finally — for commands
 * allowed to create — binding this directory to a fresh project named after
 * it.
 */
export async function resolveProject(ctx: Ctx, opts: ResolveOptions = {}): Promise<Project> {
  const projects = await ctx.client.listProjects();
  if (ctx.projectRef !== undefined) return matchRef(projects, ctx.projectRef);
  if (ctx.binding) {
    const bound = projects.find((p) => p.id === ctx.binding!.projectId);
    refuseHomeDisagreement(ctx.binding, await ctx.homes(), bound !== undefined);
    if (bound) {
      await recordDir(ctx.home, ctx.binding.root, bound.id);
      return bound;
    }
    const fromHome = await fetchFromHome(ctx.client, ctx.birthHome, ctx.binding);
    if (fromHome) {
      await recordDir(ctx.home, ctx.binding.root, fromHome.id);
      return fromHome;
    }
    refuseOfflineBirth(ctx.binding);
    if (opts.create) return materializeBinding(ctx, ctx.binding);
    throw new Error(
      `this directory is bound to project ${ctx.binding.projectId} ` +
        `(${markerFile(ctx.binding.root)}), which does not exist in this home yet — ` +
        "`isocan session start`, or any command that adds something, materializes it",
    );
  }
  const fallback = (await readConfig(ctx.home)).defaultProjectId;
  if (fallback !== undefined) return matchRef(projects, fallback);
  if (projects.length === 1) return projects[0]!;
  if (opts.create) {
    const made = await bindFresh(ctx);
    if (made) return made;
  }
  throw new Error(
    projects.length === 0
      ? "no projects yet — create one with `isocan project create <title>`"
      : "multiple projects — pass --project <id|title>, or bind this directory to one with `isocan use <project>`",
  );
}

/** Exact id, then case-insensitive title prefix. */
function matchRef(projects: Project[], ref: string): Project {
  const byId = projects.find((p) => p.id === ref);
  if (byId) return byId;
  const matches = projects.filter((p) => p.title.toLowerCase().startsWith(ref.toLowerCase()));
  if (matches.length === 1) return matches[0]!;
  if (matches.length > 1) {
    throw new Error(
      `ambiguous project "${ref}": ${matches.map((p) => `${p.id} (${p.title})`).join(", ")}`,
    );
  }
  throw new Error(`no project matches "${ref}"`);
}

/** The freshly created project, read back from the daemon — the store is the
 * truth about stamps and timestamps, so nothing here fabricates a Project. */
async function projectById(client: DaemonClient, id: string): Promise<Project> {
  const project = (await client.listProjects()).find((p) => p.id === id);
  if (!project) throw new Error(`project ${id} was created but the daemon cannot list it`);
  return project;
}

/**
 * **A marker naming a canvas this machine does not hold, on a machine that has
 * a home: ask the home for it.**
 *
 * This is the clone case — `.isocan/project.json` committed to git and checked
 * out on a second machine, Scene 0's multi-device beat. It used to need
 * nothing: the daemon enumerated its home, the canvas was in the list because
 * its link grant would admit anybody, and by the time the CLI ran the canvas
 * had already replicated. Phase 8 stage 4 stopped a replica enumerating its
 * home — a machine now mirrors what it was let INTO — so this arrival, which
 * carries an address and no admission, has to say what it wants.
 *
 * It can, and that is the whole argument: somebody put the id in this
 * directory. The marker is the hand-off. What comes back is the home's own
 * door test on the badge this daemon holds there — the same test that used to
 * run a second later when the sweep dialled the socket — so nothing is
 * admitted here that would not have been admitted then.
 *
 * **The marker's own address is the one asked** (phase 10.3), and that is what
 * turns this from a convenience into the mechanism the phase runs on: a
 * checkout naming a home this machine has never dialled is no longer a
 * refusal. The daemon opens a link to that address, is tested at its door, and
 * writes the row — nothing else on this machine moves. A marker naming no home
 * falls back to the birth default, which is what "absent means wherever the
 * daemon reading this lives" has always meant.
 *
 * **Null means "nothing to try", never "refused".** A machine with neither a
 * marker address nor a birth default has nowhere to ask (and the daemon
 * answers `not-a-replica` if asked anyway, which is a fine answer to get: this
 * is asked speculatively). A REFUSAL is thrown, because "your home will not let
 * this machine onto that canvas" is the one sentence that turns a mystifying
 * empty replica into a thing a person can act on — and the thing they act on
 * is `isocan pass`.
 *
 * **An unreachable home is thrown too, and named.** It used to be unthinkable:
 * the old refusal fired before this was ever called, so nothing downstream had
 * to think about a home that simply did not answer. Now that a marker's address
 * is dialled on sight, "nobody was home at X" is an ordinary Tuesday — and the
 * one thing it must never become is a fall-through to
 * {@link materializeBinding}, which would mint a second canvas under an id
 * whose marker promises another home. See {@link refuseOfflineBirth}.
 */
async function fetchFromHome(
  client: DaemonClient,
  birthHome: string | null,
  binding: DirBinding,
): Promise<Project | null> {
  const target = binding.home ?? birthHome;
  if (!target) return null;
  try {
    await client.joinFromHome(binding.projectId, binding.home);
  } catch (err) {
    if (err instanceof ApiError && err.code === "not-a-replica") return null;
    if (err instanceof ApiError && err.code === "home-unreachable") {
      throw new Error(
        `${target} did not answer, so ${binding.projectId} (${markerFile(binding.root)}) ` +
          `cannot be fetched: ${(err as Error).message}\n` +
          "Nothing was created here. That canvas lives at that address and this machine " +
          "will not make a second one under its id — try again when the home is up.",
      );
    }
    if (err instanceof ApiError && err.status === 404) return null;
    throw new Error(
      `${target} would not hand this machine ${binding.projectId} ` +
        `(${markerFile(binding.root)}): ${(err as Error).message}\n` +
        "If that canvas is yours, mint a pass from a session that is already on it " +
        "(`isocan pass`) and run the command it prints here.",
    );
  }
  /**
   * The home said yes; the canvas still has to travel. `join` kicks the sweep
   * rather than carrying the canvas back in its own response, because what
   * makes a canvas present on this machine is a socket and a snapshot, not a
   * JSON body — and a CLI that returned the home's row while the local store
   * was still empty would hand every command after it a canvas that is not
   * there.
   */
  const deadline = Date.now() + 15_000;
  for (;;) {
    const here = (await client.listProjects()).find((p) => p.id === binding.projectId);
    if (here) return here;
    if (Date.now() > deadline) {
      throw new Error(
        `${target} let this machine onto ${binding.projectId}, but the canvas has not ` +
          "arrived yet. It replicates in the background — try again in a moment.",
      );
    }
    await new Promise((resolve) => setTimeout(resolve, 50));
  }
}

/**
 * **A marker that promises another home is never materialized here.**
 *
 * The guard that used to be free. Before phase 10.3 the fall-through below was
 * simply unreachable for a marker naming a home — `refuseForeignHome` threw
 * first, on any address that was not the daemon's own — and `materializeBinding`
 * only ever saw markers this machine could not have got from anywhere else.
 * Narrowing that refusal to marker-against-record opened the path, so the
 * guard has to be stated rather than inherited.
 *
 * What it prevents is **offline birth of a twin**: a canvas created locally
 * under an id whose committed marker says it lives at X. Two stores would then
 * hold one id, both believing they were it, and the first sweep that met the
 * other would either refuse to dial (the daemon's arbitration rule) or, if the
 * ids ever met at a home, overwrite one of them through `adoptRemoteSnapshot`.
 * Birth while the home cannot be reached is a real and wanted thing — it is
 * phase 13's (`offline-birth.md`), where it comes with an adoption story — and
 * until then the honest answer is the refusal, by name.
 */
function refuseOfflineBirth(binding: DirBinding): void {
  if (binding.home === undefined) return;
  throw new Error(
    `${binding.projectId} lives at ${binding.home} (${markerFile(binding.root)}) and this ` +
      "machine could not get it from there. Creating it here instead would make a SECOND " +
      "canvas with that id — a twin, which is what offline birth means and which is not " +
      "built yet. Nothing was created. Fix the reach to that home, or mint a pass there " +
      "(`isocan pass`) and run the command it prints here.",
  );
}

/**
 * A marker whose project this home has never seen — a fresh clone, or a
 * teammate's directory. ADOPT the id rather than minting one: project ids
 * are what let two homes agree they are working on the same canvas, so the
 * store is created under the id the marker carries.
 *
 * `fetchFromHome` runs before it, so a marker whose canvas lives at a home this
 * machine can reach arrives by replication instead of being re-created under
 * its id — and a marker that names a home at all never reaches this function
 * at all (see {@link refuseOfflineBirth}). What is left is the case this was
 * always for: a marker that names an id and nothing else.
 */
async function materializeBinding(ctx: Ctx, binding: DirBinding): Promise<Project> {
  const title = binding.title ?? path.basename(binding.root);
  await ctx.client.sendOp(null, ctx.actor, {
    type: "project.create",
    projectId: binding.projectId,
    title,
  });
  await recordDir(ctx.home, binding.root, binding.projectId);
  console.error(
    `note: materialized "${title}" (${binding.projectId}) from ${markerFile(binding.root)}`,
  );
  return projectById(ctx.client, binding.projectId);
}

/** Bind an unbound directory: a new project named after it, a marker beside
 * it, a roster row in the home. Null when the directory refuses a marker
 * (the user's home directory, the filesystem root). */
async function bindFresh(ctx: Ctx): Promise<Project | null> {
  const root = await bindableRoot(process.cwd(), ctx.home);
  if (!root) return null;
  const projectId = newProjectId();
  const title = path.basename(root);
  // The write is the birth, and a birth that names an address FORWARDS — so
  // this one call is what makes the canvas exist at that home rather than here,
  // and the marker records the address it was born at. Nothing extra is done to
  // make that true; it falls out of the demotion, which is the argument for
  // having done the demotion in the engine rather than in each caller.
  //
  // **The address rides with the op** (phase 10.3): this directory is unbound
  // by definition — that is what `bindFresh` means — so the only assertion
  // available is the birth default, and stating it beside the create is what
  // makes the daemon write the row for the canvas coming into existence. On a
  // machine with no birth default nothing is sent, the daemon records the
  // canvas as its own, and the marker gets no `home` key: Dion's rig, byte for
  // byte what it was.
  const birth = ctx.birthHome;
  await ctx.client.sendOp(
    null,
    ctx.actor,
    { type: "project.create", projectId, title },
    undefined,
    birth ?? undefined,
  );
  const marker = { projectId, title, ...(birth ? { home: birth } : {}) };
  const file = await writeMarker(root, marker);
  await recordDir(ctx.home, root, projectId);
  console.error(`note: created "${title}" (${projectId}) for this directory — bound via ${file}`);
  ctx.binding = { root, ...marker };
  return projectById(ctx.client, projectId);
}

/**
 * The handshake's half of #60: after an agent names itself, make sure the
 * directory it landed in has a canvas. An existing binding is confirmed (and
 * its store materialized if this home has never seen it); an unbound,
 * bindable directory gets a fresh project named after it. Null when the
 * directory refuses a marker — the handshake still succeeded, there is just
 * no canvas to imply.
 */
export async function ensureDirBinding(
  client: DaemonClient,
  home: string,
  actor: Actor,
  /** The daemon's birth default — where a canvas made here, naming nothing,
   * goes. The per-canvas answers are read from the record below; this one
   * cannot be, because a canvas that does not exist yet has no row. */
  birthHome: string | null = null,
): Promise<{ project: Project; root: string; created: boolean } | null> {
  const binding = await findBinding(process.cwd(), home);
  if (binding) {
    const existing = (await client.listProjects()).find((p) => p.id === binding.projectId);
    // The same question `resolveProject` asks, asked the same way and against
    // the same record — the handshake lands in a directory nobody vetted, so it
    // is exactly as likely to meet a marker that disagrees.
    refuseHomeDisagreement(binding, await readHomeRecord(client, birthHome), existing !== undefined);
    if (existing) {
      await recordDir(home, binding.root, existing.id);
      return { project: existing, root: binding.root, created: false };
    }
    // Same order as `resolveProject`: a marker whose canvas lives at a home
    // this machine can reach is FETCHED, not re-created. `created: false`
    // because nothing was — the canvas has existed at the home all along, and
    // an agent told it created a canvas it merely joined would say so on the
    // thread.
    const fromHome = await fetchFromHome(client, birthHome, binding);
    if (fromHome) {
      await recordDir(home, binding.root, fromHome.id);
      return { project: fromHome, root: binding.root, created: false };
    }
    // And the same guard, for the same reason: this is the other place a
    // marker's id could be minted a second time locally.
    refuseOfflineBirth(binding);
    const title = binding.title ?? path.basename(binding.root);
    await client.sendOp(
      null,
      actor,
      { type: "project.create", projectId: binding.projectId, title },
      undefined,
      birthHome ?? undefined,
    );
    await recordDir(home, binding.root, binding.projectId);
    return {
      project: await projectById(client, binding.projectId),
      root: binding.root,
      created: true,
    };
  }
  const root = await bindableRoot(process.cwd(), home);
  if (!root) return null;
  const projectId = newProjectId();
  const title = path.basename(root);
  await client.sendOp(
    null,
    actor,
    { type: "project.create", projectId, title },
    undefined,
    birthHome ?? undefined,
  );
  await writeMarker(root, { projectId, title, ...(birthHome ? { home: birthHome } : {}) });
  await recordDir(home, root, projectId);
  return { project: await projectById(client, projectId), root, created: true };
}

/** Build a MetaPatch from --title/--description/--prop/--rm-prop flags. */
export function metaPatch(opts: {
  title?: string;
  description?: string;
  prop?: Record<string, string>;
  rmProp?: string[];
}): MetaPatch {
  const patch: MetaPatch = {};
  if (opts.title !== undefined) patch.title = opts.title;
  if (opts.description !== undefined) patch.description = opts.description;
  if (opts.prop && Object.keys(opts.prop).length > 0) patch.properties = opts.prop;
  if (opts.rmProp && opts.rmProp.length > 0) patch.removeProperties = opts.rmProp;
  return patch;
}
