// GENERATED by scripts/release.mjs. main's canvas-shot.mjs imports what a
// checkout has beside it; the release ships the bundle built from it.
import "../packages/cli/dist/scripts/canvas-shot.mjs";
