#!/usr/bin/env node
/**
 * **Every decision this project has taken, and where its reason lives.**
 *
 *   node scripts/decisions.mjs           # write docs/decisions.md
 *   node scripts/decisions.mjs --check   # fail if it is out of date
 *
 * #206 phase 5. The decisions index has been unstarted on the board for weeks
 * for want of somewhere to put it, and the reason it kept not getting written
 * is that it looked like a fifth artifact to keep by hand — beside the
 * research notes, the projects, the lessons and the reviews.
 *
 * **It is not.** A decision in this repository already has a shape and a
 * home: research notes and project designs carry `**Dn.**` in a `## Decisions`
 * section, and `docs/reviews/lessons.md` carries numbered lessons as
 * (shape, cost, guard). So this DERIVES, exactly as `docs/ROADMAP.md` derives
 * from front matter — and derived is what stops it becoming a fifth place that
 * disagrees with the other four.
 *
 * **What it is for.** Not reading end to end. It is for the question that has
 * no answer today: *did we already decide this, and why?* — which is asked by
 * a person about to re-litigate something, and by an agent about to rebuild
 * it. Six rebuilds of existing code in one week is the cost of not having it.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repo = fileURLToPath(new URL("..", import.meta.url));
const OUT = path.join(repo, "docs/decisions.md");
const CHECK = process.argv.includes("--check");

const BEGIN = "<!-- generated by scripts/decisions.mjs — do not edit between these markers -->";
const END = "<!-- end generated -->";

/** Markdown under `docs/`, minus the generated pages that would fold in on
 *  themselves. */
function sources() {
  const out = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        // `reviews/` holds nightly runs and is read for lessons only, below.
        if (entry.name !== "reviews" && entry.name !== "changelog") walk(full);
      } else if (entry.name.endsWith(".md") && !["ROADMAP.md", "decisions.md"].includes(entry.name)) {
        out.push(full);
      }
    }
  };
  walk(path.join(repo, "docs"));
  return out.sort();
}

/** `**D3. The canvas decides; the repo keeps.** …` — the number, the claim,
 *  and the file that argues it. The claim is the first sentence: a decision
 *  whose summary needs a paragraph was not a decision. */
export function decisions() {
  const out = [];
  for (const file of sources()) {
    const rel = path.relative(repo, file);
    const text = readFileSync(file, "utf8");
    for (const m of text.matchAll(/^\*\*(D\d+)\.\s*([^*]+?)\*\*/gm)) {
      const claim = m[2].replace(/\s+/g, " ").trim().replace(/[.:,;]$/, "");
      out.push({ id: m[1], claim, file: rel, title: titleOf(text, rel) });
    }
  }
  return out;
}

/** A numbered lesson: the shape it states, and the guard that holds it. */
export function lessons(file = path.join(repo, "docs/reviews/lessons.md")) {
  if (!existsSync(file)) return [];
  const out = [];
  for (const line of readFileSync(file, "utf8").split("\n")) {
    const m = /^\|\s*(\d+)\s*\|\s*\*\*(.+?)\*\*/.exec(line);
    if (m) out.push({ n: Number(m[1]), shape: m[2].replace(/\s+/g, " ").trim() });
  }
  return out.sort((a, b) => a.n - b.n);
}

function titleOf(text, rel) {
  return /^#\s+(.+)$/m.exec(text)?.[1]?.trim() ?? path.basename(rel, ".md");
}

const ds = decisions();
const ls = lessons();
const byFile = new Map();
for (const d of ds) {
  if (!byFile.has(d.file)) byFile.set(d.file, { title: d.title, rows: [] });
  byFile.get(d.file).rows.push(d);
}

const block = [
  BEGIN,
  "",
  `**${ds.length} decisions across ${byFile.size} documents, and ${ls.length} lessons.**`,
  "Derived from the `**Dn.**` lines each design already carries and from",
  "`docs/reviews/lessons.md` — so this cannot be more right than the thing it",
  "describes, and it is never a second place to keep one.",
  "",
  "Read it to answer *did we already decide this, and why* — the question that",
  "precedes re-litigating something, or rebuilding it.",
  "",
  "## Decisions",
  "",
];
for (const [file, { title, rows }] of [...byFile].sort()) {
  block.push(`### [${title}](${path.relative(path.join(repo, "docs"), path.join(repo, file))})`, "");
  for (const d of rows) block.push(`- **${d.id}** — ${d.claim}`);
  block.push("");
}
block.push("## Lessons", "", "The shape each one states; the cost and the guard are in the file.", "");
for (const l of ls) block.push(`- **${l.n}** — ${l.shape}`);
block.push("", END);

const rendered = block.join("\n");
const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
const head = `# Decisions\n\nWhat this project has decided, and where each argument lives. Generated —\n\`node scripts/decisions.mjs\`.\n\n`;
const next = current.includes(BEGIN)
  ? current.slice(0, current.indexOf(BEGIN)) + rendered + current.slice(current.indexOf(END) + END.length)
  : head + rendered + "\n";

if (CHECK) {
  if (next !== current) {
    console.error("docs/decisions.md is out of date — run `node scripts/decisions.mjs`");
    process.exit(1);
  }
  console.log(`docs/decisions.md — ${ds.length} decisions, ${ls.length} lessons`);
} else {
  writeFileSync(OUT, next);
  console.log(`docs/decisions.md — ${ds.length} decisions, ${ls.length} lessons`);
}
