#!/usr/bin/env node
/**
 * **The collab skill as a constant in the room module**
 * (docs/projects/room/design.md, "skill: not a dep").
 *
 * A sheep is born with `.agents/skills/isocan-collab/SKILL.md` in its pasture.
 * A host with no filesystem cannot read that file at run time, so
 * `@isocan/rc` carries its text as `COLLAB_SKILL`, generated here:
 *
 *   node scripts/rc-skill.mjs          # rewrite packages/rc/src/skill.ts
 *
 * `packages/rc/test/skill.test.ts` fails when the two disagree and names this
 * command.
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = path.dirname(fileURLToPath(new URL("../package.json", import.meta.url)));
export const SKILL_FILE = ".agents/skills/isocan-collab/SKILL.md";
export const CONSTANT_FILE = "packages/rc/src/skill.ts";

/** The module text for a skill body. JSON string escaping is valid TypeScript. */
export function skillModule(text) {
  return [
    `// GENERATED by \`node scripts/rc-skill.mjs\` from ${SKILL_FILE} — do not edit.`,
    "// packages/rc/test/skill.test.ts holds the two equal.",
    "",
    "/** The isocan collab skill's SKILL.md, for a host with no disk to read it from. */",
    `export const COLLAB_SKILL: string = ${JSON.stringify(text)};`,
    "",
  ].join("\n");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const text = readFileSync(path.join(root, SKILL_FILE), "utf8");
  writeFileSync(path.join(root, CONSTANT_FILE), skillModule(text));
  console.error(`rc-skill: wrote ${CONSTANT_FILE} (${text.length} chars from ${SKILL_FILE})`);
}
