#!/usr/bin/env node
/**
 * **The review index, derived.**
 *
 * `docs/reviews/README.md` says what its table is FOR, and it is not
 * decoration:
 *
 * > Every run **reads before it looks**. The index below is the first thing a
 * > persona opens, so a run in October knows what a run in August already
 * > measured and can say "still true", "fixed", or "worse" instead of
 * > rediscovering it.
 *
 * That made it the memory the whole persona arrangement stands on — and it was
 * hand-kept, so it stopped. `persona-run.mjs` writes a dated page and never
 * touches the index; between 24 Aug and 1 Sep it fell **four run-days
 * behind**, listing nothing from 8-29, 8-30, 8-31 or 9-01. Every run in that
 * stretch opened an index that ended before the previous week and started
 * cold, which is exactly the rediscovery the paragraph above was written to
 * prevent.
 *
 * So it is generated now, from the dated pages themselves — the same move
 * `ROADMAP.md` made for the same reason, with the same `--check` guard, since
 * a generated file nothing verifies goes stale the same way by a slower route.
 *
 *   node scripts/reviews.mjs           # rewrite the generated block
 *   node scripts/reviews.mjs --check   # fail if it is out of date, for CI
 *
 * **The hand-written rows are left alone.** The August reviews predate
 * `persona-run.mjs` and carry paragraphs of measured prose that no generator
 * could reconstruct and none should overwrite. They keep their own table below
 * the generated one; this only owns what it can derive.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repo = fileURLToPath(new URL("..", import.meta.url));
const dir = path.join(repo, "docs/reviews");
const out = path.join(dir, "README.md");

const BEGIN = "<!-- generated by scripts/reviews.mjs — do not edit between these markers -->";
const END = "<!-- end generated -->";

/** `2026-09-01-architect.md`, and `2026-08-24b-design.md` for a second run in
 * one day. The suffix is part of the date because that is how it sorts. */
const NAME = /^(\d{4}-\d{2}-\d{2}[a-z]?)-([a-z-]+)\.md$/;

/**
 * A row of a markdown table, as cells. Returns null for the `| --- |` rule and
 * for anything that is not a table row, so a caller can filter on the shape
 * rather than on the line number — the pages are generated, but a persona may
 * add prose between the tables and has.
 */
function cells(line) {
  if (!line.startsWith("|") || /^\|[\s-]+\|[\s-|]*$/.test(line)) return null;
  return line
    .slice(1, line.endsWith("|") ? -1 : undefined)
    .split("|")
    .map((c) => c.trim());
}

/** What one dated page reports. */
function read(file) {
  const text = readFileSync(path.join(dir, file), "utf8");
  // Only the automated pages have this line; the August ones are prose, and
  // this is the discriminator rather than the date, so a hand-written review
  // filed tomorrow is still left alone.
  if (!text.includes("scripts/persona-run.mjs")) return null;

  const goals = [];
  const findings = [];
  let inFindings = false;
  for (const line of text.split("\n")) {
    if (line.startsWith("## Findings")) {
      inFindings = true;
      continue;
    }
    const row = cells(line);
    if (row === null) continue;
    if (!inFindings && row.length === 4 && row[0] !== "Goal") {
      // "**MISSED**" / "held" / "instrument broken" — normalized to the word,
      // because the emphasis is presentation and the verdict is the fact.
      const verdict = row[3].replaceAll("*", "").trim();
      goals.push({ name: row[0], now: row[2], verdict });
    } else if (inFindings && row.length === 2 && row[0] !== "Finding" && row[0] !== "—") {
      findings.push({ what: row[0], outcome: row[1] });
    }
  }
  return { goals, findings };
}

const pages = [];
for (const file of readdirSync(dir)) {
  const m = NAME.exec(file);
  if (!m) continue;
  const parsed = read(file);
  if (parsed === null) continue;
  pages.push({ file, date: m[1], persona: m[2], ...parsed });
}

// Newest first, and a persona's name breaks the tie so a day's rows are stable
// rather than ordered by whatever readdir felt like.
pages.sort((a, b) => (a.date === b.date ? a.persona.localeCompare(b.persona) : b.date.localeCompare(a.date)));

const missedTotal = pages.filter((p) => p.goals.some((g) => g.verdict === "MISSED")).length;
const openTotal = pages.reduce(
  (n, p) => n + p.findings.filter((f) => f.outcome === "unanswered").length,
  0,
);
const broken = pages.filter((p) => p.goals.some((g) => g.verdict.startsWith("instrument"))).length;

const lines = [
  BEGIN,
  "",
  `**${pages.length} automated runs**, newest first. ` +
    `**${openTotal} findings unanswered** — the only thing a run wants from a person — ` +
    `and ${missedTotal} runs carrying a missed bound` +
    (broken > 0 ? `, ${broken} with a broken instrument` : "") +
    ".",
  "",
  "A missed goal is news; a broken instrument is a failure. `unanswered` is not a",
  "backlog to be cleared for tidiness — it is the row nobody has said `accepted` or",
  "`rejected` on yet, and a finding that keeps reappearing needs a guard rather than",
  "a third mention.",
  "",
  "| Date | Persona | Goals | Missed | Unanswered |",
  "| --- | --- | --- | --- | --- |",
];

for (const p of pages) {
  const missed = p.goals.filter((g) => g.verdict === "MISSED");
  const brokenHere = p.goals.filter((g) => g.verdict.startsWith("instrument"));
  const open = p.findings.filter((f) => f.outcome === "unanswered");
  const held = p.goals.filter((g) => g.verdict === "held").length;
  // A finding a bound generated says the same thing the Missed column already
  // says. Listing both makes the index a wall that reads as repetition, which
  // is how an index stops being read — so the count carries those and only a
  // finding somebody WROTE gets its words in the table.
  const fromBound = /\bis\b.*,\s*past\b/;
  const written = open.filter((f) => !fromBound.test(f.what));
  lines.push(
    `| [${p.date}](${p.file}) | ${p.persona} | ` +
      // `market-researcher` has no standing number and the README says so out
      // loud. "0/0 held" would read as a persona whose goals all failed.
      (p.goals.length === 0 ? "no standing number" : `${held}/${p.goals.length} held`) +
      " | " +
      // Name the goal and its value: "MISSED" alone sends a reader to the file
      // to find out what, which is the friction that makes an index unread.
      (missed.length === 0 && brokenHere.length === 0
        ? "—"
        : [
            ...missed.map((g) => `**${g.name}** — ${g.now}`),
            ...brokenHere.map((g) => `**${g.name}** — instrument broken`),
          ].join("; ")) +
      " | " +
      (open.length === 0
        ? "—"
        : `${open.length}` + (written.length > 0 ? ` — ${written.map((f) => f.what).join("; ")}` : "")) +
      " |",
  );
}

lines.push("", END);
const block = lines.join("\n");

const current = existsSync(out) ? readFileSync(out, "utf8") : "";
if (!current.includes(BEGIN) || !current.includes(END)) {
  console.error(
    `docs/reviews/README.md has no generated block — add these two lines where the index belongs:\n${BEGIN}\n${END}`,
  );
  process.exit(1);
}
const before = current.slice(0, current.indexOf(BEGIN));
const after = current.slice(current.indexOf(END) + END.length);
const page = before + block + after;

if (process.argv.includes("--check")) {
  if (current !== page) {
    console.error("docs/reviews/README.md is out of date — run `node scripts/reviews.mjs`");
    process.exit(1);
  }
  console.log("docs/reviews/README.md is current");
  process.exit(0);
}

writeFileSync(out, page);
console.log(
  `docs/reviews/README.md — ${pages.length} runs, ${openTotal} findings unanswered, ${missedTotal} runs with a missed bound`,
);
