#!/usr/bin/env node
/**
 * **The review index, derived.**
 *
 * `docs/reviews/README.md` says what its table is FOR, and it is not
 * decoration:
 *
 * > Every run **reads before it looks**. The index below is the first thing a
 * > persona opens, so a run in October knows what a run in August already
 * > measured and can say "still true", "fixed", or "worse" instead of
 * > rediscovering it.
 *
 * That made it the memory the whole persona arrangement stands on — and it was
 * hand-kept, so it stopped. `persona-run.mjs` writes a dated page and never
 * touches the index; between 24 Aug and 1 Sep it fell **four run-days
 * behind**, listing nothing from 8-29, 8-30, 8-31 or 9-01. Every run in that
 * stretch opened an index that ended before the previous week and started
 * cold, which is exactly the rediscovery the paragraph above was written to
 * prevent.
 *
 * So it is generated now, from the dated pages themselves — the same move
 * `ROADMAP.md` made for the same reason, with the same `--check` guard, since
 * a generated file nothing verifies goes stale the same way by a slower route.
 *
 *   node scripts/reviews.mjs           # rewrite the generated block
 *   node scripts/reviews.mjs --check   # fail if it is out of date, for CI
 *
 * **The hand-written rows are left alone.** The August reviews predate
 * `persona-run.mjs` and carry paragraphs of measured prose that no generator
 * could reconstruct and none should overwrite. They keep their own table below
 * the generated one; this only owns what it can derive.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repo = fileURLToPath(new URL("..", import.meta.url));
const dir = path.join(repo, "docs/reviews");
const out = path.join(dir, "README.md");

const BEGIN = "<!-- generated by scripts/reviews.mjs — do not edit between these markers -->";
const END = "<!-- end generated -->";

/** `2026-09-01-architect.md`, and `2026-08-24b-design.md` for a second run in
 * one day. The suffix is part of the date because that is how it sorts. */
const NAME = /^(\d{4}-\d{2}-\d{2}[a-z]?)-([a-z-]+)\.md$/;

/**
 * A row of a markdown table, as cells. Returns null for the `| --- |` rule and
 * for anything that is not a table row, so a caller can filter on the shape
 * rather than on the line number — the pages are generated, but a persona may
 * add prose between the tables and has.
 */
function cells(line) {
  if (!line.startsWith("|") || /^\|[\s-]+\|[\s-|]*$/.test(line)) return null;
  return line
    .slice(1, line.endsWith("|") ? -1 : undefined)
    .split("|")
    .map((c) => c.trim());
}

/** What one dated page reports. */
function read(file) {
  const text = readFileSync(path.join(dir, file), "utf8");
  // Only the automated pages have this line; the August ones are prose, and
  // this is the discriminator rather than the date, so a hand-written review
  // filed tomorrow is still left alone.
  if (!text.includes("scripts/persona-run.mjs")) return null;

  const goals = [];
  const findings = [];
  let inFindings = false;
  for (const line of text.split("\n")) {
    if (line.startsWith("## Findings")) {
      inFindings = true;
      continue;
    }
    const row = cells(line);
    if (row === null) continue;
    if (!inFindings && row.length === 4 && row[0] !== "Goal") {
      // "**MISSED**" / "held" / "instrument broken" — normalized to the word,
      // because the emphasis is presentation and the verdict is the fact.
      const verdict = row[3].replaceAll("*", "").trim();
      goals.push({ name: row[0], now: row[2], verdict });
    } else if (inFindings && row.length === 2 && row[0] !== "Finding" && row[0] !== "—") {
      findings.push({ what: row[0], outcome: row[1] });
    }
  }
  return { goals, findings };
}

/**
 * Every automated run, newest first — a persona's name breaks the tie so a
 * day's rows are stable rather than ordered by whatever readdir felt like.
 *
 * Exported because `test/review-queue.test.ts` asks the same pages a different
 * question, and a second parser would be a second definition of `unanswered`.
 */
export function reviewPages() {
  const pages = [];
  for (const file of readdirSync(dir)) {
    const m = NAME.exec(file);
    if (!m) continue;
    const parsed = read(file);
    if (parsed === null) continue;
    pages.push({ file, date: m[1], persona: m[2], ...parsed });
  }
  pages.sort((a, b) => (a.date === b.date ? a.persona.localeCompare(b.persona) : b.date.localeCompare(a.date)));
  return pages;
}

/**
 * **Whether somebody has actually said something about a finding.**
 *
 * Answered means the cell begins with `accepted` or `rejected` — a decision,
 * usually followed by the reason. **Everything else is unanswered**, including
 * an empty cell, the bare word `unanswered`, `TBD`, and a misspelling of
 * `accepted`.
 *
 * That direction is the point. This started as `outcome === "unanswered"`, an
 * exact match, and the first attempt to prove the guard could catch anything
 * failed against it: back-dating a real finding to `unanswered — the metric
 * was retired` left a row that was plainly unanswered and that neither the
 * index nor the guard could see. An exact match on the OPEN state fails open —
 * any trailing word, and a finding disappears from the queue silently. Testing
 * for the CLOSED state fails closed: a typo makes the queue louder, not
 * shorter, which is the only safe direction for something whose job is to
 * notice that nobody is looking.
 *
 * It reclassifies nothing today: all 26 findings on file begin with one of the
 * two words.
 */
export function isAnswered(outcome) {
  const said = (outcome ?? "").trim().toLowerCase();
  return said.startsWith("accepted") || said.startsWith("rejected");
}

/**
 * **How long a finding may sit before it reddens a commit.**
 *
 * The number that makes the queue able to fail (#197, D6). Chosen against the
 * failure it exists to prevent: on 6 September 2026, 26 findings sat
 * `unanswered` across **six nights** while the number one of them described
 * went 600,420 → 768,993. Every report was correct, every report was written,
 * and nothing made anybody read them. So the bound has to be shorter than six
 * — a limit the failure would have passed is not a limit.
 *
 * Three days: a finding filed on Monday night is due by Thursday night, which
 * is two clear days plus the night it arrived. Deliberately uncomfortable.
 * `unanswered` is not a backlog to clear for tidiness — answering is one word,
 * `accepted` or `rejected`, and the point of the discomfort is that a person
 * decides rather than the report scrolling away.
 *
 * Raising this is allowed and is one line with a reason beside it, the same
 * shape as `CEILING` in `test/bundle-budget.test.ts`. What must not happen
 * again is six nights of correct reports nobody read.
 */
export const ANSWER_DAYS = 3;

/**
 * **The same question, asked again every night.**
 *
 * A persona writes one finding per MISSED goal, every run — so a bound that
 * stays missed writes a new `unanswered` row nightly. Answered per row, that
 * is a daily chore for a question nobody's answer changed, and a guard that
 * nags every morning is a guard somebody turns off. `docs/reviews/README.md`
 * says the same thing from the other side: *a finding that keeps reappearing
 * needs a guard rather than a third mention.*
 *
 * So a bound-derived finding is identified by **the goal and the bound**, not
 * by its text — the value moves nightly and the question does not. Answer "the
 * entry chunk is past 640000" once and later nights are the same answer still
 * standing.
 *
 * Returns null for anything a person wrote in their own words, which has no
 * identity beyond itself and is asked once.
 */
export function findingKey(what) {
  const m = /^(.*) is (-?[\d.]+)\S* , ?past (-?[\d.]+)/.exec(what.replace(/,\s*past/, " , past"));
  return m ? { goal: m[1].trim(), bound: m[3], value: Number(m[2]) } : null;
}

/**
 * **How much worse a number may get before the answer stops covering it.**
 *
 * The failure this exists for: on 6 September the entry chunk went
 * 600,420 → 768,993 across six nights while every report said MISSED and
 * nobody read them. Identity alone would have let one early "accepted" cover
 * all six, which is the treadmill fixed by creating a coma.
 *
 * Ten per cent. The 6 Sep drift was +28%, so it would have been asked again —
 * which is the test of a number like this: it has to catch the thing it was
 * written for.
 *
 * Assumes an `at most` goal, where growth is worse. Every goal declared today
 * is one; a future `at least` goal would need the sign flipped, and it should
 * fail loudly here rather than silently cover a collapse.
 */
export const WORSE_BY = 0.1;

/**
 * **A question asked a third time is asking for a guard** (#197 phase 4).
 *
 * The README has said so since the index existed — *a finding that keeps
 * reappearing needs a guard rather than a third mention* — and nothing
 * counted. So the pattern was only visible to somebody who read seventy-eight
 * rows and noticed the same words in six of them, which is exactly the noticing
 * that did not happen while the entry chunk grew by a hundred kilobytes.
 *
 * Three, because that is the number the sentence above already names. Below it
 * a repeat is a bound that is still missed; at it, the repetition is the
 * finding.
 */
export const REPEAT_FROM = 3;

/**
 * **How many runs have carried each question, for the questions carried more
 * than once.**
 *
 * Identity is `findingKey`'s and nothing else — the same fold `findUnanswered`
 * settles answers by, so "the same question" means one thing here, in the
 * guard, and in the index. A second notion of sameness is how six nights of
 * one question read as six findings.
 *
 * **Answered nights count.** The claim is not "nobody has replied" — that is
 * the Unanswered column's job — it is "this keeps coming back", and a question
 * answered `accepted` three months running is the treadmill this exists to
 * make visible. `answered` rides along so a reader can tell the two apart
 * without a second pass.
 *
 * Counted by PAGE rather than by finding: a persona that wrote the same bound
 * twice in one run has still only asked once that night.
 */
export function askedAgain(pages, from = REPEAT_FROM) {
  const seen = new Map();
  // Oldest first, so `first` and `last` mean what they say however the caller
  // ordered its pages.
  for (const page of [...pages].sort((a, b) => a.date.localeCompare(b.date))) {
    const here = new Map();
    for (const finding of page.findings) {
      const key = findingKey(finding.what);
      if (key === null) continue;
      here.set(`${key.goal}|${key.bound}`, { key, finding });
    }
    for (const [id, { key, finding }] of here) {
      const row = seen.get(id) ?? {
        goal: key.goal, bound: key.bound, runs: 0, first: page.date, last: page.date,
        firstValue: key.value, value: key.value, answered: false,
      };
      row.runs += 1;
      row.last = page.date;
      row.value = key.value;
      row.answered = isAnswered(finding.outcome);
      seen.set(id, row);
    }
  }
  return [...seen.values()]
    .filter((row) => row.runs >= from)
    .sort((a, b) => b.runs - a.runs || a.goal.localeCompare(b.goal));
}

/**
 * The findings that have gone past their answer-by date.
 *
 * Pure, and takes `today`, so the guard can be shown to actually catch
 * something — a test that only ever asserts "the real queue is empty" would
 * pass just as happily if this function always returned nothing, which is the
 * vacuous guard this repo has already deleted two of.
 *
 * A finding a missed bound generated counts the same as one a persona wrote.
 * The index tells them apart for display, because a bound's row repeats what
 * the Missed column already said — but 6 September's unanswered pile was
 * mostly bound rows, so excluding them here would exempt the exact case.
 */
export function findUnanswered(pages, days = ANSWER_DAYS, today = new Date()) {
  /**
   * Every answered bound-finding, by identity, remembering the SMALLEST value
   * anybody said yes to. Smallest rather than latest: the question a person
   * answered was about the number in front of them, and drift is measured from
   * there rather than from whatever it has since become.
   */
  const settled = new Map();
  for (const page of pages) {
    for (const finding of page.findings) {
      if (!isAnswered(finding.outcome)) continue;
      const key = findingKey(finding.what);
      if (key === null) continue;
      const id = `${key.goal}|${key.bound}`;
      const seen = settled.get(id);
      if (seen === undefined || key.value < seen) settled.set(id, key.value);
    }
  }

  const late = [];
  for (const page of pages) {
    // `2026-08-24b` — a second run in one day. The suffix sorts; it is not a date.
    const stamped = Date.parse(`${page.date.slice(0, 10)}T00:00:00Z`);
    if (Number.isNaN(stamped)) continue;
    const age = Math.floor((today.getTime() - stamped) / 86_400_000);
    if (age <= days) continue;
    for (const finding of page.findings) {
      if (isAnswered(finding.outcome)) continue;
      const key = findingKey(finding.what);
      if (key !== null) {
        const answeredAt = settled.get(`${key.goal}|${key.bound}`);
        // Somebody has already answered this question at this bound, and the
        // number has not got materially worse since. The answer stands.
        if (answeredAt !== undefined && key.value <= answeredAt * (1 + WORSE_BY)) continue;
      }
      late.push({ file: page.file, persona: page.persona, date: page.date, what: finding.what, age });
    }
  }
  // Oldest first: the one that has been ignored longest is the one to read.
  return late.sort((a, b) => b.age - a.age);
}

const { cadenceRows, firedCrons } = await import("./cadence.mjs");

const pages = reviewPages();

const missedTotal = pages.filter((p) => p.goals.some((g) => g.verdict === "MISSED")).length;
const openTotal = pages.reduce(
  (n, p) => n + p.findings.filter((f) => !isAnswered(f.outcome)).length,
  0,
);
const broken = pages.filter((p) => p.goals.some((g) => g.verdict.startsWith("instrument"))).length;

const lines = [
  BEGIN,
  "",
  `**${pages.length} automated runs**, newest first. ` +
    `**${openTotal} findings unanswered** — the only thing a run wants from a person — ` +
    `and ${missedTotal} runs carrying a missed bound` +
    (broken > 0 ? `, ${broken} with a broken instrument` : "") +
    ".",
  "",
  "A missed goal is news; a broken instrument is a failure. `unanswered` is not a",
  "backlog to be cleared for tidiness — it is the row nobody has said `accepted` or",
  "`rejected` on yet, and a finding that keeps reappearing needs a guard rather than",
  "a third mention.",
  "",
  `**A finding older than ${ANSWER_DAYS} days with no answer fails \`npm test\`**`,
  "(`test/review-queue.test.ts`, #197). The column used to be ignorable, so it was",
  "decorative: 26 findings sat here across six nights while the number one of them",
  "described grew by a hundred kilobytes.",
  "",
];

/**
 * **Asked again** (#197 phase 4), above the runs rather than inside them.
 *
 * A count in a cell of a seventy-eight-row table is a number nobody adds up,
 * and adding it up by eye is the work this exists to remove. As its own short
 * list it makes one claim a person can act on: these questions have been asked
 * this many times, so they want a guard rather than another answer.
 *
 * Omitted entirely when nothing repeats, because a heading over an empty table
 * is a section that trains people to skip the region it lives in.
 */
const repeats = askedAgain(pages);
if (repeats.length > 0) {
  lines.push(
    `**${repeats.length} question${repeats.length === 1 ? " has" : "s have"} been asked ` +
      `${REPEAT_FROM} nights or more.**`,
    "A number that keeps missing the same bound stops being news: it is a bound to",
    "either enforce or move, and the repetition is the argument for doing one of them.",
    "`accepted` on the newest night does not end it — an answer that has to be given",
    "again every week is the treadmill, not the fix.",
    "",
    "| Asked | Bound | Nights | Now | First asked |",
    "| --- | --- | --- | --- | --- |",
  );
  for (const row of repeats) {
    lines.push(
      `| ${row.goal} | ${row.bound} | **${row.runs}** | ${row.value}` +
        (row.answered ? " (answered)" : "") +
        ` | ${row.first}, at ${row.firstValue} |`,
    );
  }
  lines.push("");
}

/**
 * **When each persona says it runs, against when it last did** (#206 phase 1).
 *
 * Above the runs because it is a fact about the MACHINE rather than about any
 * one night: a cron that silently stops looks exactly like a quiet week, and
 * until this was written nothing anywhere reconciled a declaration against the
 * past. `trigger` is read by `isocan persona ls` and the board's panel, and
 * both only display it — nothing schedules from it.
 *
 * The staleness column reports and does not fail: a run whose pull request is
 * still open reads a day behind through no fault of the persona. What IS
 * guarded is the declaration itself (`test/cadence.test.ts`), because declared
 * twice and not declared at all are true or false in the tree and nowhere
 * else.
 */
const cadence = cadenceRows();
const offCadence = cadence.filter((r) => r.verdict !== "agrees");
lines.push(
  // Only the schedules a persona actually names: the repository has other
  // crons (the changelog, the grades) and listing them here would be a
  // sentence about the wrong thing.
  `**${cadence.length} personas, fired by ` +
    [...new Set(cadence.map((r) => r.cron).filter(Boolean))]
      .map((cron) => `\`${cron}\` (${firedCrons().get(cron) ?? "nothing"})`)
      .join(" and ") +
    ".**" +
    (offCadence.length === 0
      ? " Every one declares the cadence that actually runs it."
      : ` ${offCadence.length} ${offCadence.length === 1 ? "declares" : "declare"} something else.`),
  "",
  "| Persona | Says | Last ran | |",
  "| --- | --- | --- | --- |",
);
for (const row of cadence) {
  const when = row.lastRan ? `${row.lastRan} · ${row.ageDays}d ago` : "never";
  lines.push(
    `| ${row.name} | \`${row.cron ?? "—"}\` | ${when} | ${row.verdict === "agrees" ? "" : `**${row.verdict}**`} |`,
  );
}
lines.push("");

lines.push(
  "| Date | Persona | Goals | Missed | Unanswered |",
  "| --- | --- | --- | --- | --- |",
);

for (const p of pages) {
  const missed = p.goals.filter((g) => g.verdict === "MISSED");
  const brokenHere = p.goals.filter((g) => g.verdict.startsWith("instrument"));
  const open = p.findings.filter((f) => !isAnswered(f.outcome));
  const held = p.goals.filter((g) => g.verdict === "held").length;
  // A finding a bound generated says the same thing the Missed column already
  // says. Listing both makes the index a wall that reads as repetition, which
  // is how an index stops being read — so the count carries those and only a
  // finding somebody WROTE gets its words in the table.
  //
  // Asked through `findingKey` rather than a regex of its own. It was a second
  // pattern (`/\bis\b.*,\s*past\b/`) for a question this file already
  // answers, and it was looser — no digits required — so the two could disagree
  // about whether a sentence containing "is … past" was a bound. Two answers to
  // "is this from a bound" is how one row ends up counted here and not there.
  const written = open.filter((f) => findingKey(f.what) === null);
  lines.push(
    `| [${p.date}](${p.file}) | ${p.persona} | ` +
      // `market-researcher` has no standing number and the README says so out
      // loud. "0/0 held" would read as a persona whose goals all failed.
      (p.goals.length === 0 ? "no standing number" : `${held}/${p.goals.length} held`) +
      " | " +
      // Name the goal and its value: "MISSED" alone sends a reader to the file
      // to find out what, which is the friction that makes an index unread.
      (missed.length === 0 && brokenHere.length === 0
        ? "—"
        : [
            ...missed.map((g) => `**${g.name}** — ${g.now}`),
            ...brokenHere.map((g) => `**${g.name}** — instrument broken`),
          ].join("; ")) +
      " | " +
      (open.length === 0
        ? "—"
        : `${open.length}` + (written.length > 0 ? ` — ${written.map((f) => f.what).join("; ")}` : "")) +
      " |",
  );
}

lines.push("", END);
const block = lines.join("\n");

// Everything above is pure: reading pages and building a string. Everything
// below writes files and calls `process.exit`, so it runs only when this is
// the program — `test/review-queue.test.ts` imports the module for its parser
// and must not rewrite the index or take the process down with it.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}

function main() {
const current = existsSync(out) ? readFileSync(out, "utf8") : "";
if (!current.includes(BEGIN) || !current.includes(END)) {
  console.error(
    `docs/reviews/README.md has no generated block — add these two lines where the index belongs:\n${BEGIN}\n${END}`,
  );
  process.exit(1);
}
const before = current.slice(0, current.indexOf(BEGIN));
const after = current.slice(current.indexOf(END) + END.length);
const page = before + block + after;

if (process.argv.includes("--check")) {
  if (current !== page) {
    console.error("docs/reviews/README.md is out of date — run `node scripts/reviews.mjs`");
    process.exit(1);
  }
  console.log("docs/reviews/README.md is current");
  process.exit(0);
}

writeFileSync(out, page);
console.log(
  `docs/reviews/README.md — ${pages.length} runs, ${openTotal} findings unanswered, ${missedTotal} runs with a missed bound`,
);
}
