#!/usr/bin/env node
/**
 * **The roadmap, derived.**
 *
 * It used to be written: `docs/projects/README.md` carried a "where it stands"
 * column, research docs carried a `**Where this stands, …**` paragraph, and an
 * artifact outside the repo restated both. Three copies, kept in step by hand,
 * and the third went stale silently because nothing read it.
 *
 * `docs/research/2026-08-26-attaching-a-directory.md` is what that costs: on
 * the day this was written it held **two contradictory verdicts, both dated
 * the same day** — "not built" at the top and "1, 2 and 3 are built" in the
 * middle. Neither was lying; one was just older, and nothing could tell.
 *
 * So status lives in the doc, in front matter, where it cannot drift from the
 * thing it describes — and this reads it. `docs/ROADMAP.md` is generated and
 * says so; editing it by hand is editing the wrong file.
 *
 *   node scripts/roadmap.mjs           # write docs/ROADMAP.md
 *   node scripts/roadmap.mjs --check   # fail if it is out of date, for CI
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const repo = fileURLToPath(new URL("..", import.meta.url));
const cli = path.join(repo, "packages/cli/bin/isocan.js");

/**
 * Front matter is read through the CLI so there is ONE reader — core's
 * `docStatus`. A second little parser here is how the roadmap would come to
 * disagree with the thing it is a view of, which is the bug it exists to fix.
 */
function statusOf(file) {
  const out = execFileSync("node", [cli, "--json", "doc", "status", file], {
    cwd: repo,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  return JSON.parse(out);
}

const ORDER = ["journey.md", "design.md", "plan.md", "phases.md"];

function collect() {
  const docs = [];
  const rdir = path.join(repo, "docs/research");
  for (const name of readdirSync(rdir).filter((f) => f.endsWith(".md") && f !== "README.md").sort()) {
    const rel = `docs/research/${name}`;
    docs.push({ kind: "research", rel, title: titleOf(path.join(repo, rel)), ...statusOf(rel) });
  }
  const pdir = path.join(repo, "docs/projects");
  for (const name of readdirSync(pdir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()) {
    const primary = ORDER.find((f) => existsSync(path.join(pdir, name, f)));
    if (!primary) continue;
    const rel = `docs/projects/${name}/${primary}`;
    docs.push({ kind: "project", rel, title: name, ...statusOf(rel) });
  }
  return docs;
}

/** The first heading, which is the doc's own name for itself. */
function titleOf(file) {
  const line = readFileSync(file, "utf8")
    .split("\n")
    .find((l) => l.startsWith("# "));
  return line ? line.slice(2).trim() : path.basename(file);
}

const docs = collect();
const byState = {};
for (const d of docs) (byState[d.status] ??= []).push(d);
const count = (s) => (byState[s] ?? []).length;
const left = count("open") + count("designed") + count("partial") + count("blocked");

const LABEL = {
  built: "Built",
  noted: "Noted — read, owing nothing",
  partial: "Partly built",
  designed: "Designed, not built",
  blocked: "Blocked",
  open: "No verdict recorded",
  superseded: "Superseded",
};

const lines = [
  "<!-- Generated by scripts/roadmap.mjs. Do not edit — edit the front matter",
  "     of the document itself, which is where its status lives. -->",
  "# Roadmap",
  "",
  "Every research note and every project, by where it stands. **Derived**: the",
  "status of a thing lives in that thing's front matter, so it cannot drift from",
  "what it describes. Run `node scripts/roadmap.mjs` after changing one.",
  "",
  `**${count("built")} built · ${left} still open** — of which ${count("partial")} partly`,
  `built, ${count("designed")} designed, ${count("blocked")} blocked, and`,
  `**${count("open")} with no verdict recorded at all**, which is the number worth`,
  "watching: an untriaged doc is not a doc nobody needs, it is a doc nobody has",
  "read lately.",
  "",
  `${count("noted")} more are \`noted\` — read, absorbed, owing nothing — and`,
  `${count("superseded")} superseded. Neither counts as done: reading is not building,`,
  "and the done column should not be flattered by either.",
  "",
];

for (const state of ["blocked", "partial", "designed", "open", "built", "noted", "superseded"]) {
  const group = byState[state];
  if (!group || group.length === 0) continue;
  lines.push(`## ${LABEL[state]} <sub>${group.length}</sub>`, "");
  lines.push("| | What | Since | |", "| --- | --- | --- | --- |");
  for (const d of group.sort((a, b) => a.title.localeCompare(b.title))) {
    const why = d.blockedBy ? `blocked by ${d.blockedBy}` : (d.note ?? "");
    const see = d.see.length ? ` · see ${d.see.join(", ")}` : "";
    lines.push(
      `| ${d.kind === "project" ? "**project**" : "research"} | [${d.title}](${d.rel}) | ${d.since ?? "—"} | ${why}${see} |`,
    );
  }
  lines.push("");
}

const page = lines.join("\n");
const out = path.join(repo, "docs/ROADMAP.md");

if (process.argv.includes("--check")) {
  const current = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (current !== page) {
    console.error("docs/ROADMAP.md is out of date — run `node scripts/roadmap.mjs`");
    process.exit(1);
  }
  console.log("docs/ROADMAP.md is current");
  process.exit(0);
}

writeFileSync(out, page);
console.log(`docs/ROADMAP.md — ${docs.length} docs, ${count("built")} built, ${left} open`);
