import { promises as fs } from "node:fs";
import path from "node:path";
import type { Actor, HomesResponse, Canvas } from "@isocan/core";
import { DEFAULT_PORT, newCanvasId, normalizeHomeUrl } from "@isocan/core";
import { paths, readConfigFile, stalenessOf } from "@isocan/server";
import { ApiError, type Health } from "./routes.ts";
import { DaemonClient } from "./client.ts";
import { requireIdentity, resolveIdentity, retireStrandedIdentities } from "./identity.ts";
import { DIRECT_VAR, resolveDeclared } from "./direct.ts";
import {
  bindableRoot,
  findBinding,
  markerFile,
  recordDir,
  writeMarker,
  type DirBinding,
} from "@isocan/server";

export interface Ctx {
  client: DaemonClient;
  actor: Actor;
  /**
   * Which harness this CLI is — `claude-code`, `codex`, `gemini` — or null
   * for the machine's person, who is not one.
   *
   * Resolved once, here, because it is already known here:
   * `resolveIdentity` has to work out which harness session this process
   * belongs to in order to find the actor at all. Everything downstream
   * (presence, so `who` and the facepile can say which agent is which) was
   * otherwise going to re-derive it from the environment and get it wrong in
   * the one case that matters — an agent launched by another agent sees both
   * sets of variables.
   */
  harness: string | null;
  json: boolean;
  home: string;
  canvasRef?: string;
  /** The directory's canvas, when the cwd sits under a `.isocan/project.json`
   * marker (#60). Resolved once per command; null outside any bound tree. */
  binding: DirBinding | null;
  /**
   * **Where a canvas born here, naming nothing, would be born** — and nothing
   * else.
   *
   * Read once per command off the health route rather than from this machine's
   * own config, deliberately: what matters is what the daemon ACTUALLY is — a
   * CLI whose config was edited five minutes ago and a daemon that has been
   * running since Tuesday must not disagree about where a canvas goes.
   *
   * **It was called `homeUrl` and it was renamed on purpose** (phase 10.3).
   * The old name invited exactly one mistake: using a daemon-wide value to
   * build A SPECIFIC CANVAS's address. On a machine with two homes that prints
   * `dev.isocan.io/p/<a canvas that lives on this laptop>` — the cheerful
   * wrong address, generated by us, in the one string a person pastes to
   * another person. The rename made the typechecker walk every reader so each
   * one could be decided rather than assumed, and the readers that wanted a
   * canvas's home now say so: {@link Ctx.homeOf}.
   */
  birthHome: string | null;
  /**
   * **Where THIS canvas lives** — the address to build its page URL from, or
   * null when this daemon is its home (so the caller's own base is the one
   * origin for it).
   *
   * Off `GET /api/homes`, fetched at most once per command and only when
   * somebody asks: a read that prints no address needs no round trip.
   */
  homeOf(canvasId: string): Promise<string | null>;
  /** The whole record, for the two callers that need more than one canvas's
   * answer — `isocan status`'s role line and the refusal below. */
  homes(): Promise<HomeRecord>;
}

/**
 * **What this machine has recorded about where its canvases live** — `GET
 * /api/homes`, plus the one thing the route cannot say about itself.
 *
 * The three-state answer is the whole reason this is not a plain map. For one
 * canvas id there are three different facts, and phase 10.3's refusals turn on
 * telling them apart:
 *
 * - **a row naming an address** — this machine has been to that home for this
 *   canvas and wrote it down;
 * - **a row naming `null`** — this daemon IS its home, recorded at birth
 *   (deliberately explicit: it is what stops a link's sweep later claiming a
 *   locally-born canvas under "no row, so adopt it");
 * - **no row at all** — this machine has never had anything to do with this
 *   canvas. That is the cloned-marker case, and it must JOIN rather than
 *   refuse.
 */
export interface HomeRecord {
  /** Where a canvas born here, naming nothing, goes. */
  birth: string | null;
  /** Every home this daemon dials, whether its last poll was answered, and —
   * the half the poll cannot speak for — whether each canvas's own socket is
   * carrying anything. See `CanvasLinkState`. */
  links: HomesResponse["links"];
  /** This canvas's row: an address, `null` for "here", `undefined` for "no row
   * — this machine has never recorded anything about that canvas". */
  rowFor(canvasId: string): string | null | undefined;
  /** Every row, for the summaries. */
  rows: Record<string, string | null>;
  /**
   * **This daemon predates `GET /api/homes`**, so every answer above is
   * inferred from the health route's one field.
   *
   * Not a hypothetical: a daemon outlives the CLI that started it, which is
   * the entire reason `warnIfStale` exists — an upgraded CLI talking to
   * yesterday's daemon is the ordinary case for a few minutes. On such a
   * daemon there is exactly one home and it is the one the health route names,
   * so treating every canvas as living there is not a guess, it is that
   * daemon's actual model. Getting this wrong the other way would print
   * `127.0.0.1` for canvases that live at a home — the cheerful wrong address
   * again, introduced by an upgrade.
   */
  legacy: boolean;
}

/**
 * **The default-canvas key in `~/.isocan/config.json`** — a deliberate
 * holdout from phase 13.5's rename: it is a KEY in a hand-edited file that
 * already exists on every machine. Renaming it would have an upgraded CLI
 * read an old file, find no key, and quietly forget the home default — the
 * same argument `HomeConfig.home` is written on.
 *
 * Declared here because {@link resolveCanvas} is its reader; the CLI's
 * `ConfigFile` extends this so `isocan use` writes the same spelling.
 */
export interface HomeDefaultConfig {
  defaultProjectId?: string;
}

/**
 * **Which address this CLI's commands go to** — the one computation behind
 * every `DaemonClient` in the process.
 *
 * It was `http://127.0.0.1:${port}` written out at ten call sites, which was
 * fine while there was one answer. Phase 11 gave it a second, so the rule
 * lives in one place: ten sites each learning it separately is ten chances for
 * a command to reach the wrong replica, and the failure would be silent
 * because both answers are real daemons that will cheerfully serve the
 * request.
 *
 * Direct mode's address, in order: whatever said "direct" if it named an
 * address, then the directory marker's `home`. The marker is what makes the
 * cloned-repo case work with nothing but `ISOCAN_DIRECT=1` in the
 * environment — the committed `.isocan/project.json` already carries the
 * canvas id and the home address, which is exactly what Scene 6 leans on when
 * it says the marker "corroborates" them.
 */
export async function resolveBase(
  isocanHome: string,
  port: number,
  binding: DirBinding | null,
): Promise<{ base: string; direct: string | null }> {
  const declared = await resolveDeclared(isocanHome);
  if (declared?.mode === "direct") {
    // The address, in order: whatever declared it, if it named one; then the
    // directory marker's `home`. The marker is what makes the cloned-repo case
    // work with nothing but `ISOCAN_DIRECT=1` in the environment — the
    // committed `.isocan/project.json` already carries the canvas id and the
    // home address, which is exactly what Scene 6 leans on when it says the
    // marker "corroborates" them.
    const at = declared.at ?? binding?.home ?? null;
    if (at) return { base: at, direct: at };
    // Direct was asked for and no address could be found. Refusing here rather
    // than falling back to 127.0.0.1 is the whole care: a silent fallback would
    // start a daemon on a machine that said not to, and the agent would work a
    // local replica of nothing while believing it was on the team's canvas.
    throw new Error(
      `${DIRECT_VAR} says this machine runs no daemon, but nothing says which home to ` +
        "speak to: it does not name an address, there is no `direct` in " +
        `${paths.configFile(isocanHome)}, and no .isocan/project.json marker in this ` +
        `directory names one. Set the address itself ` +
        `(${DIRECT_VAR}=https://isocan.io), or run \`isocan setup <canvas address> --direct\` here.`,
    );
  }
  return { base: `http://127.0.0.1:${port}`, direct: null };
}

/**
 * {@link resolveBase} for the commands that build a client outside a `Ctx` —
 * `identity`, `whoami`, `clone`, and the two best-effort helpers behind a
 * rename. They each resolve the directory's marker for themselves, which is
 * one extra walk up the tree and buys the thing that matters: there is no
 * second spelling of "which address does this machine talk to".
 */
export async function baseForCwd(
  isocanHome: string,
  port: number,
): Promise<{ base: string; direct: string | null }> {
  return resolveBase(isocanHome, port, await findBinding(process.cwd(), isocanHome));
}

/**
 * What a resolution needs to know from its caller, and nothing about how the
 * caller learned it. The CLI's `makeCtx` reads these off a commander
 * `Command`; that read is the whole of what stayed behind in the split
 * (iso-api phase 1) — everything from here down resolves home, daemon, badge,
 * actor and canvas from the directory and the environment alone.
 */
export interface CtxOptions {
  /** Machine-readable output. A presentation flag, carried through because
   * `Ctx` is what every command holds — see the phase's findings. */
  json?: boolean;
  port?: number;
  canvasRef?: string;
}

export async function resolveCtx(options: CtxOptions = {}): Promise<Ctx> {
  const home = paths.isocanHome();
  const port = options.port ?? Number(process.env.ISOCAN_PORT ?? DEFAULT_PORT);
  /**
   * **The marker, read before the client rather than after it** (phase 11).
   *
   * It used to be resolved near the bottom, where only `Ctx.binding` wanted
   * it. Direct mode gave it a second reader that has to run first: on a
   * machine that has said "no daemon" without saying where to go, the
   * directory's `.isocan/project.json` is what names the home — which is the
   * whole of how a cloned repo in a fresh cloud workspace knows its address.
   */
  const binding = await findBinding(process.cwd(), home);
  const { base, direct } = await resolveBase(home, port, binding);
  const client = new DaemonClient(base, home);
  // A person at a keyboard is asked once, up front. Everyone else is asked
  // only if it turns out to matter: looking (`ls`, `canvas list`, `show`)
  // stamps nothing, and an agent should be able to see where it has landed
  // before it decides what to call itself. The getter is what makes that
  // lazy — reads never touch `actor`, so they never demand one.
  await retireStrandedIdentities(process.cwd(), home);
  const known = await resolveIdentity(client, home);
  const actor = known?.actor ?? (process.stdin.isTTY ? await requireIdentity(client, home) : null);
  const harness = known?.harness ?? null;
  // A direct machine has no daemon to ensure, and starting one would be the
  // one thing it has said not to do.
  if (!direct) await client.ensureDaemon();
  // One health call, two answers. It was already being made for the staleness
  // warning; asking it again for the home address would be a second round trip
  // on every command for a field that travels in the same body.
  const health = await client.healthz().catch(() => null);
  // Staleness is "the daemon holding this port is an older build than this
  // CLI", and on a direct machine that sentence has no referent — the process
  // answering is somebody else's home, and whether ITS build matches this CLI
  // is the wire-version question, which the door answers with a 426 and an
  // upgrade command. Asking `stalenessOf` here would compare a laptop's CLI to
  // a server's deploy and warn about it on every command.
  if (!direct) await warnIfStale(health, home);
  await warnIfBehind(health, home);
  const birthHome = health?.home ?? null;
  // Lazily, and at most once: `GET /api/homes` is a second round trip, and
  // most commands never name an address. `ls` should not pay for `share`.
  let record: Promise<HomeRecord> | null = null;
  const homes = () => (record ??= readHomeRecord(client, birthHome));
  // Nothing is claimed here. Mechanism 5 asks the badge to vouch for whoever
  // this command speaks as — but a read stamps nothing and names nobody, and
  // an eager claim on every command would put an actors-log entry behind
  // `ls`. `resolveIdentity` has already told the client HOW to claim; the
  // home asking is what makes it happen, exactly once per badge.
  return {
    client,
    get actor(): Actor {
      if (!actor) {
        throw new Error(
          'no identity yet — `isocan identity --name "Your Name" --session` names this agent',
        );
      }
      return actor;
    },
    json: options.json ?? false,
    harness,
    home,
    binding,
    birthHome,
    homes,
    async homeOf(canvasId: string): Promise<string | null> {
      return homeAddressOf(await homes(), canvasId);
    },
    ...(options.canvasRef !== undefined ? { canvasRef: options.canvasRef } : {}),
  };
}

/**
 * The record, read once, with the old daemon's answer standing in when the
 * route is not there — see {@link HomeRecord.legacy}.
 *
 * Exported because `ensureDirBinding` runs outside a `Ctx` (the session
 * handshake builds no context) and must ask the same question the same way. A
 * second spelling of "where does this canvas live" is how the two paths would
 * come to disagree.
 */
export async function readHomeRecord(
  client: DaemonClient,
  birthHome: string | null,
): Promise<HomeRecord> {
  const answer = await client.homes().catch(() => null);
  const rows = answer?.canvases ?? {};
  return {
    birth: answer ? answer.birth : birthHome,
    links: answer?.links ?? [],
    rows,
    legacy: answer === null,
    rowFor: (canvasId: string) => rows[canvasId],
  };
}

/** Where this canvas's page is served from, or null for "this daemon". The one
 * computation behind every address the CLI prints. */
export function homeAddressOf(record: HomeRecord, canvasId: string): string | null {
  if (record.legacy) return record.birth;
  return record.rowFor(canvasId) ?? null;
}

/**
 * **The marker and the record disagree about where this canvas lives.** Refuse,
 * naming both, and migrate nothing.
 *
 * It used to compare the marker against the DAEMON — "this canvas lives at X
 * and this daemon answers to Y" — and under one home per daemon that was the
 * only comparison available. Phase 10.3 made the home a property of the canvas,
 * so the question moved: the marker is compared against **this machine's own
 * row for that canvas** (`homes.json`, read through `GET /api/homes`). The
 * rename is how every call site got visited rather than grepped for.
 *
 * The five cases, and which of them is a refusal:
 *
 * - **The marker names no home.** Not a refusal, and never was: "absent means
 *   wherever the daemon reading this lives" is the marker's own sentence, and
 *   every marker written before phase 6 lacks the key. The record decides.
 * - **The marker agrees with the row.** The ordinary case.
 * - **The marker names a home this machine has never recorded anything about.**
 *   *Not a refusal — a JOIN.* This is the case the phase exists for: a repo
 *   cloned onto a second machine, whose `.isocan/project.json` says the canvas
 *   lives at dev. `fetchFromHome` asks the daemon to go and get it, the far
 *   door decides, and the row is written. Nothing else on this machine moves.
 * - **The marker names a home, and this machine's row names a DIFFERENT one.**
 *   Refused. An edited marker, two clones that disagree, a canvas re-homed
 *   somewhere else while this checkout slept.
 * - **The marker names a home, and this machine's row says the canvas is
 *   LOCAL** (or holds it with no row at all — a pre-10.3 canvas). Refused, same
 *   sentence: a canvas materialized here under an id whose marker promises
 *   another home is a twin, and pretending either half is authoritative is how
 *   one of them gets overwritten.
 *
 * Moving a canvas between homes is **re-homing** — a thick replica offering
 * its store to a new home and rewriting the marker (innkeeper.md) — and it is
 * phase 13's. What it moves is the WORK and not the desk: badges, grants,
 * attestations and the claims binding actors to badges all stay behind. That
 * is not a migration a command can perform as a side effect of somebody
 * running `isocan ls` in the wrong directory, so nothing here migrates
 * anything. The two addresses are both printed because the interesting
 * question is always which of them is the surprise.
 */
function refuseHomeDisagreement(
  binding: DirBinding,
  record: HomeRecord,
  /** Does this daemon actually hold that canvas? The one fact `GET /api/homes`
   * cannot supply: a canvas held here since before phase 10.3 has no row, and
   * "no row" would otherwise read as "never heard of it", which is the join
   * case rather than the disagreement. */
  heldHere: boolean,
  /**
   * **Whose answer this record is** — the address the client asked.
   *
   * A `null` row does not mean "local machine"; it means *"the daemon
   * answering is this canvas's home"*, and until phase 11 those were the same
   * sentence because the daemon answering was always `127.0.0.1`. On a direct
   * machine it is the home itself, so the home's `null` for its OWN canvas —
   * which is the truth, plainly stated — read as a disagreement with a marker
   * naming that very home, and refused the command that `setup` had just
   * written the marker for. Every command after a successful arrival failed.
   *
   * Found by walking Scene 6 rather than by a test: `direct.test.ts` wrote its
   * own marker and never went through the arrival that writes `home` into one.
   */
  base: string,
): void {
  if (binding.home === undefined) return; // an older marker; it names no home
  const row = record.legacy ? record.birth : record.rowFor(binding.canvasId);
  // No row and not on this machine: nothing to disagree with. `fetchFromHome`
  // takes it from here, and the home the marker names is the one it asks.
  if (row === undefined && !heldHere) return;
  // `null` resolves to whoever answered, which is what it has always meant.
  // In daemon mode that is `127.0.0.1:<port>`, so a marker naming a remote
  // home still disagrees exactly as it did before; in direct mode it is the
  // home, and the two agree because they are the same address.
  const recorded = row ?? base;
  if (normalizeHomeUrl(recorded) === normalizeHomeUrl(binding.home)) return;
  const mine =
    row === null || row === undefined
      ? `the daemon at ${base} holds that canvas as its OWN (it is its home)`
      : `this machine has that canvas recorded as living at ${recorded}`;
  throw new Error(
    `this directory's canvas lives at ${binding.home} (${markerFile(binding.root)}), but ` +
      `${mine}. Those cannot both be true, and nothing here will guess: moving a canvas ` +
      "between homes is re-homing, a deliberate act that carries the work and leaves the " +
      "desk behind. Either the marker is stale and belongs corrected in git, or this " +
      `machine's record is (\`isocan home\` shows every canvas and where it lives).`,
  );
}

/**
 * A daemon outlives the command that started it, so an upgrade leaves the old
 * one holding the port — silently, since `ensureDaemon` only starts one when
 * nothing answers. Say so, once per daemon: an agent runs dozens of commands
 * and a line on every one of them is noise, but never saying it at all is how
 * you spend an afternoon debugging yesterday's build.
 */
async function warnIfStale(health: Health | null, home: string): Promise<void> {
  try {
    if (!health) return;
    const { stale, why } = stalenessOf(health);
    if (!stale) return;
    const marker = path.join(home, ".stale-warned");
    const said = await fs.readFile(marker, "utf8").catch(() => "");
    if (said.trim() === health.startedAt) return;
    await fs.writeFile(marker, health.startedAt).catch(() => {});
    console.error(`note: ${why} — \`isocan restart\` to run this one.`);
  } catch {
    // Never let a courtesy check break a command.
  }
}

/**
 * **The third kind of stale, reported once per verdict** (auto-upgrade phase
 * 2): this copy disagrees with the home it is talking to.
 *
 * `warnIfStale`'s sibling, and the differences from it are the phase:
 *
 * - **Keyed on the pair of shas, not on the daemon.** `warnIfStale` keys on
 *   `startedAt` because the thing it reports is the daemon. A daemon lives for
 *   days while its home moves about twice a day, so the same key here would
 *   report the first skew and then stay silent through every later one.
 * - **It names a command and does not instruct.** Who may act on it is a
 *   separate rule: in notify mode the upgrade decision belongs to a person
 *   even when the reader is an agent, and an agent that upgrades itself on
 *   seeing this line has re-implemented auto mode without its controls.
 * - **The `--json` field is the primary surface.** This line's real audience
 *   is a person reading the transcript of an agent's session; the field on
 *   `isocan status --json` is what an agent reads.
 *
 * No verdict, no line — and no line either when the verdict is that this copy
 * is current, because "you are current" is not news and printing it on the one
 * machine whose home has stopped answering is exactly the false success this
 * project's standing lesson names.
 */
async function warnIfBehind(health: Health | null, home: string): Promise<void> {
  try {
    const verdict = health?.upgrade;
    if (!verdict?.available) return;
    const pair = `${verdict.mine}->${verdict.homeCommit}`;
    const marker = path.join(home, ".upgrade-noted");
    const said = await fs.readFile(marker, "utf8").catch(() => "");
    if (said.trim() === pair) return;
    await fs.writeFile(marker, pair).catch(() => {});
    // A home running the OLDER build is a notice, never a downgrade: builds
    // come from the release branch, and pointing at `isocan upgrade` here
    // would name a command that cannot do what the line implies.
    const next =
      verdict.direction === "ahead"
        ? "your home is the older build"
        : "`isocan upgrade` catches up";
    console.error(`note: ${verdict.why} — ${next}.`);
  } catch {
    // Never let a courtesy check break a command.
  }
}

export interface ResolveOptions {
  /** May this resolution CREATE the directory's canvas: materialize a
   * marker whose store is missing here (a fresh clone), or bind an unbound
   * directory to a brand-new canvas. Passed by the commands that can put
   * something onto an empty canvas — and the session handshake — never by
   * reads, so `ls` in a stray directory cannot mint canvases. */
  create?: boolean;
}

/**
 * Which canvas a command means (#60). In order: --canvas says so; the
 * directory says so (the nearest `.isocan/project.json` marker, git-style
 * walk-up); the home default (`isocan use --home`), consulted only OUTSIDE
 * bound directories; the only canvas there is; and finally — for commands
 * allowed to create — binding this directory to a fresh canvas named after
 * it.
 */
export async function resolveCanvas(ctx: Ctx, opts: ResolveOptions = {}): Promise<Canvas> {
  const canvases = await ctx.client.listCanvases();
  if (ctx.canvasRef !== undefined) return matchRef(canvases, ctx.canvasRef);
  if (ctx.binding) {
    const bound = canvases.find((p) => p.id === ctx.binding!.canvasId);
    refuseHomeDisagreement(ctx.binding, await ctx.homes(), bound !== undefined, ctx.client.base);
    if (bound) {
      await recordDir(ctx.home, ctx.binding.root, bound.id);
      return bound;
    }
    const fromHome = await fetchFromHome(ctx.client, ctx.birthHome, ctx.binding);
    if (fromHome) {
      await recordDir(ctx.home, ctx.binding.root, fromHome.id);
      return fromHome;
    }
    refuseOfflineBirth(ctx.binding);
    if (opts.create) return materializeBinding(ctx, ctx.binding);
    throw new Error(
      `this directory is bound to canvas ${ctx.binding.canvasId} ` +
        `(${markerFile(ctx.binding.root)}), which does not exist in this home yet — ` +
        "`isocan session start`, or any command that adds something, materializes it",
    );
  }
  const fallback = (await readConfigFile<HomeDefaultConfig>(ctx.home)).defaultProjectId;
  if (fallback !== undefined) return matchRef(canvases, fallback);
  if (canvases.length === 1) return canvases[0]!;
  if (opts.create) {
    const made = await bindFresh(ctx);
    if (made) return made;
  }
  throw new Error(
    canvases.length === 0
      ? "no canvases yet — create one with `isocan canvas create <title>`"
      : "multiple canvases — pass --canvas <id|title>, or bind this directory to one with `isocan use <canvas>`",
  );
}

/** Exact id, then case-insensitive title prefix. */
/** A canvas by id or by a unique title prefix — the one spelling of "which
 *  canvas did they mean", shared so `--to` on a copy means exactly what
 *  `--canvas` means everywhere else. */
export function matchRef(canvases: Canvas[], ref: string): Canvas {
  const byId = canvases.find((p) => p.id === ref);
  if (byId) return byId;
  const matches = canvases.filter((p) => p.title.toLowerCase().startsWith(ref.toLowerCase()));
  if (matches.length === 1) return matches[0]!;
  if (matches.length > 1) {
    throw new Error(
      `ambiguous canvas "${ref}": ${matches.map((p) => `${p.id} (${p.title})`).join(", ")}`,
    );
  }
  throw new Error(`no canvas matches "${ref}"`);
}

/** The freshly created canvas, read back from the daemon — the store is the
 * truth about stamps and timestamps, so nothing here fabricates a Canvas. */
async function canvasById(client: DaemonClient, id: string): Promise<Canvas> {
  const canvas = (await client.listCanvases()).find((p) => p.id === id);
  if (!canvas) throw new Error(`canvas ${id} was created but the daemon cannot list it`);
  return canvas;
}

/**
 * **A marker naming a canvas this machine does not hold, on a machine that has
 * a home: ask the home for it.**
 *
 * This is the clone case — `.isocan/project.json` committed to git and checked
 * out on a second machine, Scene 0's multi-device beat. It used to need
 * nothing: the daemon enumerated its home, the canvas was in the list because
 * its link grant would admit anybody, and by the time the CLI ran the canvas
 * had already replicated. Phase 8 stage 4 stopped a replica enumerating its
 * home — a machine now mirrors what it was let INTO — so this arrival, which
 * carries an address and no admission, has to say what it wants.
 *
 * It can, and that is the whole argument: somebody put the id in this
 * directory. The marker is the hand-off. What comes back is the home's own
 * door test on the badge this daemon holds there — the same test that used to
 * run a second later when the sweep dialled the socket — so nothing is
 * admitted here that would not have been admitted then.
 *
 * **The marker's own address is the one asked** (phase 10.3), and that is what
 * turns this from a convenience into the mechanism the phase runs on: a
 * checkout naming a home this machine has never dialled is no longer a
 * refusal. The daemon opens a link to that address, is tested at its door, and
 * writes the row — nothing else on this machine moves. A marker naming no home
 * falls back to the birth default, which is what "absent means wherever the
 * daemon reading this lives" has always meant.
 *
 * **Null means "nothing to try", never "refused".** A machine with neither a
 * marker address nor a birth default has nowhere to ask (and the daemon
 * answers `not-a-replica` if asked anyway, which is a fine answer to get: this
 * is asked speculatively). A REFUSAL is thrown, because "your home will not let
 * this machine onto that canvas" is the one sentence that turns a mystifying
 * empty replica into a thing a person can act on — and the thing they act on
 * is `isocan pass`.
 *
 * **An unreachable home is thrown too, and named.** It used to be unthinkable:
 * the old refusal fired before this was ever called, so nothing downstream had
 * to think about a home that simply did not answer. Now that a marker's address
 * is dialled on sight, "nobody was home at X" is an ordinary Tuesday — and the
 * one thing it must never become is a fall-through to
 * {@link materializeBinding}, which would mint a second canvas under an id
 * whose marker promises another home. See {@link refuseOfflineBirth}.
 */
async function fetchFromHome(
  client: DaemonClient,
  birthHome: string | null,
  binding: DirBinding,
): Promise<Canvas | null> {
  const target = binding.home ?? birthHome;
  if (!target) return null;
  try {
    await client.joinFromHome(binding.canvasId, binding.home);
  } catch (err) {
    if (err instanceof ApiError && err.code === "not-a-replica") return null;
    if (err instanceof ApiError && err.code === "home-unreachable") {
      throw new Error(
        `${target} did not answer, so ${binding.canvasId} (${markerFile(binding.root)}) ` +
          `cannot be fetched: ${(err as Error).message}\n` +
          "Nothing was created here. That canvas lives at that address and this machine " +
          "will not make a second one under its id — try again when the home is up.",
      );
    }
    if (err instanceof ApiError && err.status === 404) return null;
    throw new Error(
      `${target} would not hand this machine ${binding.canvasId} ` +
        `(${markerFile(binding.root)}): ${(err as Error).message}\n` +
        "If that canvas is yours, mint a pass from a session that is already on it " +
        "(`isocan pass`) and run the command it prints here.",
    );
  }
  /**
   * The home said yes; the canvas still has to travel. `join` kicks the sweep
   * rather than carrying the canvas back in its own response, because what
   * makes a canvas present on this machine is a socket and a snapshot, not a
   * JSON body — and a CLI that returned the home's row while the local store
   * was still empty would hand every command after it a canvas that is not
   * there.
   */
  const deadline = Date.now() + 15_000;
  for (;;) {
    const here = (await client.listCanvases()).find((p) => p.id === binding.canvasId);
    if (here) return here;
    if (Date.now() > deadline) {
      throw new Error(
        `${target} let this machine onto ${binding.canvasId}, but the canvas has not ` +
          "arrived yet. It replicates in the background — try again in a moment.",
      );
    }
    await new Promise((resolve) => setTimeout(resolve, 50));
  }
}

/**
 * **A marker that promises another home is never materialized here.**
 *
 * The guard that used to be free. Before phase 10.3 the fall-through below was
 * simply unreachable for a marker naming a home — `refuseForeignHome` threw
 * first, on any address that was not the daemon's own — and `materializeBinding`
 * only ever saw markers this machine could not have got from anywhere else.
 * Narrowing that refusal to marker-against-record opened the path, so the
 * guard has to be stated rather than inherited.
 *
 * What it prevents is **offline birth of a twin**: a canvas created locally
 * under an id whose committed marker says it lives at X. Two stores would then
 * hold one id, both believing they were it, and the first sweep that met the
 * other would either refuse to dial (the daemon's arbitration rule) or, if the
 * ids ever met at a home, overwrite one of them through `adoptRemoteSnapshot`.
 * Birth while the home cannot be reached is a real and wanted thing — it is
 * phase 13's (`offline-birth.md`), where it comes with an adoption story — and
 * until then the honest answer is the refusal, by name.
 */
function refuseOfflineBirth(binding: DirBinding): void {
  if (binding.home === undefined) return;
  throw new Error(
    `${binding.canvasId} lives at ${binding.home} (${markerFile(binding.root)}) and this ` +
      "machine could not get it from there. Creating it here instead would make a SECOND " +
      "canvas with that id — a twin, which is what offline birth means and which is not " +
      "built yet. Nothing was created. Fix the reach to that home, or mint a pass there " +
      "(`isocan pass`) and run the command it prints here.",
  );
}

/**
 * A marker whose canvas this home has never seen — a fresh clone, or a
 * teammate's directory. ADOPT the id rather than minting one: canvas ids
 * are what let two homes agree they are working on the same canvas, so the
 * store is created under the id the marker carries.
 *
 * `fetchFromHome` runs before it, so a marker whose canvas lives at a home this
 * machine can reach arrives by replication instead of being re-created under
 * its id — and a marker that names a home at all never reaches this function
 * at all (see {@link refuseOfflineBirth}). What is left is the case this was
 * always for: a marker that names an id and nothing else.
 */
async function materializeBinding(ctx: Ctx, binding: DirBinding): Promise<Canvas> {
  const title = binding.title ?? path.basename(binding.root);
  await ctx.client.sendOp(null, ctx.actor, {
    type: "project.create",
    canvasId: binding.canvasId,
    title,
  });
  await recordDir(ctx.home, binding.root, binding.canvasId);
  console.error(
    `note: materialized "${title}" (${binding.canvasId}) from ${markerFile(binding.root)}`,
  );
  return canvasById(ctx.client, binding.canvasId);
}

/** Bind an unbound directory: a new canvas named after it, a marker beside
 * it, a roster row in the home. Null when the directory refuses a marker
 * (the user's home directory, the filesystem root). */
async function bindFresh(ctx: Ctx): Promise<Canvas | null> {
  const root = await bindableRoot(process.cwd(), ctx.home);
  if (!root) return null;
  const canvasId = newCanvasId();
  const title = path.basename(root);
  // The write is the birth, and a birth that names an address FORWARDS — so
  // this one call is what makes the canvas exist at that home rather than here,
  // and the marker records the address it was born at. Nothing extra is done to
  // make that true; it falls out of the demotion, which is the argument for
  // having done the demotion in the engine rather than in each caller.
  //
  // **The address rides with the op** (phase 10.3): this directory is unbound
  // by definition — that is what `bindFresh` means — so the only assertion
  // available is the birth default, and stating it beside the create is what
  // makes the daemon write the row for the canvas coming into existence. On a
  // machine with no birth default nothing is sent, the daemon records the
  // canvas as its own, and the marker gets no `home` key: Dion's rig, byte for
  // byte what it was.
  const birth = ctx.birthHome;
  await ctx.client.sendOp(
    null,
    ctx.actor,
    { type: "project.create", canvasId, title },
    undefined,
    birth ?? undefined,
  );
  const marker = { canvasId, title, ...(birth ? { home: birth } : {}) };
  const file = await writeMarker(root, marker);
  await recordDir(ctx.home, root, canvasId);
  console.error(`note: created "${title}" (${canvasId}) for this directory — bound via ${file}`);
  ctx.binding = { root, ...marker };
  return canvasById(ctx.client, canvasId);
}

/**
 * The handshake's half of #60: after an agent names itself, make sure the
 * directory it landed in has a canvas. An existing binding is confirmed (and
 * its store materialized if this home has never seen it); an unbound,
 * bindable directory gets a fresh canvas named after it. Null when the
 * directory refuses a marker — the handshake still succeeded, there is just
 * no canvas to imply.
 */
export async function ensureDirBinding(
  client: DaemonClient,
  home: string,
  actor: Actor,
  /** The daemon's birth default — where a canvas made here, naming nothing,
   * goes. The per-canvas answers are read from the record below; this one
   * cannot be, because a canvas that does not exist yet has no row. */
  birthHome: string | null = null,
): Promise<{ canvas: Canvas; root: string; created: boolean } | null> {
  const binding = await findBinding(process.cwd(), home);
  if (binding) {
    const existing = (await client.listCanvases()).find((p) => p.id === binding.canvasId);
    // The same question `resolveCanvas` asks, asked the same way and against
    // the same record — the handshake lands in a directory nobody vetted, so it
    // is exactly as likely to meet a marker that disagrees.
    refuseHomeDisagreement(
      binding,
      await readHomeRecord(client, birthHome),
      existing !== undefined,
      client.base,
    );
    if (existing) {
      await recordDir(home, binding.root, existing.id);
      return { canvas: existing, root: binding.root, created: false };
    }
    // Same order as `resolveCanvas`: a marker whose canvas lives at a home
    // this machine can reach is FETCHED, not re-created. `created: false`
    // because nothing was — the canvas has existed at the home all along, and
    // an agent told it created a canvas it merely joined would say so on the
    // thread.
    const fromHome = await fetchFromHome(client, birthHome, binding);
    if (fromHome) {
      await recordDir(home, binding.root, fromHome.id);
      return { canvas: fromHome, root: binding.root, created: false };
    }
    // And the same guard, for the same reason: this is the other place a
    // marker's id could be minted a second time locally.
    refuseOfflineBirth(binding);
    const title = binding.title ?? path.basename(binding.root);
    await client.sendOp(
      null,
      actor,
      { type: "project.create", canvasId: binding.canvasId, title },
      undefined,
      birthHome ?? undefined,
    );
    await recordDir(home, binding.root, binding.canvasId);
    return {
      canvas: await canvasById(client, binding.canvasId),
      root: binding.root,
      created: true,
    };
  }
  const root = await bindableRoot(process.cwd(), home);
  if (!root) return null;
  const canvasId = newCanvasId();
  const title = path.basename(root);
  await client.sendOp(
    null,
    actor,
    { type: "project.create", canvasId, title },
    undefined,
    birthHome ?? undefined,
  );
  await writeMarker(root, { canvasId, title, ...(birthHome ? { home: birthHome } : {}) });
  await recordDir(home, root, canvasId);
  return { canvas: await canvasById(client, canvasId), root, created: true };
}
