import type { Actor, HomesResponse, Canvas } from "../../core/src/index.js";
import { DaemonClient } from "./client.js";
import { type ExplicitIdentity } from "./identity.js";
import { type DirBinding } from "../../server/src/index.js";
export interface Ctx {
    client: DaemonClient;
    actor: Actor;
    /**
     * Which harness this CLI is — `claude-code`, `codex`, `gemini` — or null
     * for the machine's person, who is not one.
     *
     * Resolved once, here, because it is already known here:
     * `resolveIdentity` has to work out which harness session this process
     * belongs to in order to find the actor at all. Everything downstream
     * (presence, so `who` and the facepile can say which agent is which) was
     * otherwise going to re-derive it from the environment and get it wrong in
     * the one case that matters — an agent launched by another agent sees both
     * sets of variables.
     */
    harness: string | null;
    home: string;
    canvasRef?: string;
    /** The directory's canvas, when the cwd sits under a `.isocan/project.json`
     * marker (#60). Resolved once per command; null outside any bound tree. */
    binding: DirBinding | null;
    /**
     * **Where a canvas born here, naming nothing, would be born** — and nothing
     * else.
     *
     * Read once per command off the health route rather than from this machine's
     * own config, deliberately: what matters is what the daemon ACTUALLY is — a
     * CLI whose config was edited five minutes ago and a daemon that has been
     * running since Tuesday must not disagree about where a canvas goes.
     *
     * **It was called `homeUrl` and it was renamed on purpose** (phase 10.3).
     * The old name invited exactly one mistake: using a daemon-wide value to
     * build A SPECIFIC CANVAS's address. On a machine with two homes that prints
     * `dev.isocan.io/p/<a canvas that lives on this laptop>` — the cheerful
     * wrong address, generated by us, in the one string a person pastes to
     * another person. The rename made the typechecker walk every reader so each
     * one could be decided rather than assumed, and the readers that wanted a
     * canvas's home now say so: {@link Ctx.homeOf}.
     */
    birthHome: string | null;
    /**
     * **Where THIS canvas lives** — the address to build its page URL from, or
     * null when this daemon is its home (so the caller's own base is the one
     * origin for it).
     *
     * Off `GET /api/homes`, fetched at most once per command and only when
     * somebody asks: a read that prints no address needs no round trip.
     */
    homeOf(canvasId: string): Promise<string | null>;
    /** The whole record, for the two callers that need more than one canvas's
     * answer — `isocan status`'s role line and the refusal below. */
    homes(): Promise<HomeRecord>;
}
/**
 * **What this machine has recorded about where its canvases live** — `GET
 * /api/homes`, plus the one thing the route cannot say about itself.
 *
 * The three-state answer is the whole reason this is not a plain map. For one
 * canvas id there are three different facts, and phase 10.3's refusals turn on
 * telling them apart:
 *
 * - **a row naming an address** — this machine has been to that home for this
 *   canvas and wrote it down;
 * - **a row naming `null`** — this daemon IS its home, recorded at birth
 *   (deliberately explicit: it is what stops a link's sweep later claiming a
 *   locally-born canvas under "no row, so adopt it");
 * - **no row at all** — this machine has never had anything to do with this
 *   canvas. That is the cloned-marker case, and it must JOIN rather than
 *   refuse.
 */
export interface HomeRecord {
    /** Where a canvas born here, naming nothing, goes. */
    birth: string | null;
    /** Every home this daemon dials, whether its last poll was answered, and —
     * the half the poll cannot speak for — whether each canvas's own socket is
     * carrying anything. See `CanvasLinkState`. */
    links: HomesResponse["links"];
    /** This canvas's row: an address, `null` for "here", `undefined` for "no row
     * — this machine has never recorded anything about that canvas". */
    rowFor(canvasId: string): string | null | undefined;
    /** Every row, for the summaries. */
    rows: Record<string, string | null>;
    /**
     * **This daemon predates `GET /api/homes`**, so every answer above is
     * inferred from the health route's one field.
     *
     * Not a hypothetical: a daemon outlives the CLI that started it, which is
     * the entire reason `warnIfStale` exists — an upgraded CLI talking to
     * yesterday's daemon is the ordinary case for a few minutes. On such a
     * daemon there is exactly one home and it is the one the health route names,
     * so treating every canvas as living there is not a guess, it is that
     * daemon's actual model. Getting this wrong the other way would print
     * `127.0.0.1` for canvases that live at a home — the cheerful wrong address
     * again, introduced by an upgrade.
     */
    legacy: boolean;
}
/**
 * **The default-canvas key in `~/.isocan/config.json`** — a deliberate
 * holdout from phase 13.5's rename: it is a KEY in a hand-edited file that
 * already exists on every machine. Renaming it would have an upgraded CLI
 * read an old file, find no key, and quietly forget the home default — the
 * same argument `HomeConfig.home` is written on.
 *
 * Declared here because {@link resolveCanvas} is its reader; the CLI's
 * `ConfigFile` extends this so `isocan use` writes the same spelling.
 */
export interface HomeDefaultConfig {
    defaultProjectId?: string;
}
/**
 * **Which address this CLI's commands go to** — the one computation behind
 * every `DaemonClient` in the process.
 *
 * It was `http://127.0.0.1:${port}` written out at ten call sites, which was
 * fine while there was one answer. Phase 11 gave it a second, so the rule
 * lives in one place: ten sites each learning it separately is ten chances for
 * a command to reach the wrong replica, and the failure would be silent
 * because both answers are real daemons that will cheerfully serve the
 * request.
 *
 * Direct mode's address, in order: whatever said "direct" if it named an
 * address, then the directory marker's `home`. The marker is what makes the
 * cloned-repo case work with nothing but `ISOCAN_DIRECT=1` in the
 * environment — the committed `.isocan/project.json` already carries the
 * canvas id and the home address, which is exactly what Scene 6 leans on when
 * it says the marker "corroborates" them.
 */
export declare function resolveBase(isocanHome: string, port: number, binding: DirBinding | null): Promise<{
    base: string;
    direct: string | null;
}>;
/**
 * {@link resolveBase} for the commands that build a client outside a `Ctx` —
 * `identity`, `whoami`, `clone`, and the two best-effort helpers behind a
 * rename. They each resolve the directory's marker for themselves, which is
 * one extra walk up the tree and buys the thing that matters: there is no
 * second spelling of "which address does this machine talk to".
 */
export declare function baseForCwd(isocanHome: string, port: number): Promise<{
    base: string;
    direct: string | null;
}>;
/**
 * What a resolution needs to know from its caller, and nothing about how the
 * caller learned it. The CLI's `makeCtx` reads these off a commander
 * `Command`; that read is the whole of what stayed behind in the split
 * (iso-api phase 1) — everything from here down resolves home, daemon, badge,
 * actor and canvas from the directory and the environment alone.
 */
export interface CtxOptions {
    port?: number;
    canvasRef?: string;
    /**
     * A stated identity instead of the ambient walk — `connect({ identity })`.
     * The named session must already be claimed; when it is not, no actor
     * resolves (and there is no fallback to the machine's person — a script
     * that says who it is must never quietly run as somebody else).
     */
    identity?: ExplicitIdentity;
    /**
     * May a person at a TTY be asked for a name — the CLI's first-run flow.
     * Defaults on; `connect()` turns it off, because an API call must never
     * wait on a keyboard. (`--json` used to ride through here as well; it is
     * the CLI's presentation flag and lives on the CLI's own Ctx now — the
     * phase 1 finding, resolved by the split it predicted.)
     */
    interactive?: boolean;
}
export declare function resolveCtx(options?: CtxOptions): Promise<Ctx>;
/**
 * The record, read once, with the old daemon's answer standing in when the
 * route is not there — see {@link HomeRecord.legacy}.
 *
 * Exported because `ensureDirBinding` runs outside a `Ctx` (the session
 * handshake builds no context) and must ask the same question the same way. A
 * second spelling of "where does this canvas live" is how the two paths would
 * come to disagree.
 */
export declare function readHomeRecord(client: DaemonClient, birthHome: string | null): Promise<HomeRecord>;
/** Where this canvas's page is served from, or null for "this daemon". The one
 * computation behind every address the CLI prints. */
export declare function homeAddressOf(record: HomeRecord, canvasId: string): string | null;
export interface ResolveOptions {
    /** May this resolution CREATE the directory's canvas: materialize a
     * marker whose store is missing here (a fresh clone), or bind an unbound
     * directory to a brand-new canvas. Passed by the commands that can put
     * something onto an empty canvas — and the session handshake — never by
     * reads, so `ls` in a stray directory cannot mint canvases. */
    create?: boolean;
}
/**
 * Which canvas a command means (#60). In order: --canvas says so; the
 * directory says so (the nearest `.isocan/project.json` marker, git-style
 * walk-up); the home default (`isocan use --home`), consulted only OUTSIDE
 * bound directories; the only canvas there is; and finally — for commands
 * allowed to create — binding this directory to a fresh canvas named after
 * it.
 */
export declare function resolveCanvas(ctx: Ctx, opts?: ResolveOptions): Promise<Canvas>;
/** Exact id, then case-insensitive title prefix. */
/** A canvas by id or by a unique title prefix — the one spelling of "which
 *  canvas did they mean", shared so `--to` on a copy means exactly what
 *  `--canvas` means everywhere else. */
export declare function matchRef(canvases: Canvas[], ref: string): Canvas;
/**
 * The handshake's half of #60: after an agent names itself, make sure the
 * directory it landed in has a canvas. An existing binding is confirmed (and
 * its store materialized if this home has never seen it); an unbound,
 * bindable directory gets a fresh canvas named after it. Null when the
 * directory refuses a marker — the handshake still succeeded, there is just
 * no canvas to imply.
 */
export declare function ensureDirBinding(client: DaemonClient, home: string, actor: Actor, 
/** The daemon's birth default — where a canvas made here, naming nothing,
 * goes. The per-canvas answers are read from the record below; this one
 * cannot be, because a canvas that does not exist yet has no row. */
birthHome?: string | null): Promise<{
    canvas: Canvas;
    root: string;
    created: boolean;
} | null>;
