// Independent synthetic phase 3 proof. Run from the repository with node --import tsx.
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {auditScreen} from '../../../packages/core/src/designaudit.ts';
const base = {name:'Acme Contract Probe', colors:{ink:'#202020',accent:'#0000ff'}, spacing:{sm:'8px',md:'16px'}, rounded:{control:'8px',large:'16px'}, typography:{title:{fontSize:'24px',fontWeight:600},display:{fontSize:'32px',fontWeight:700}}};
const lint = {version:1,literals:'allow', recipes:{Button:{owns:{padding:'{spacing.md}','border-radius':'{rounded.control}'},allow:['margin','align-self'],treatments:{compact:{padding:'{spacing.sm}'}}},Title:{owns:{'font-weight':'{typography.title.fontWeight}'},allow:['font-size']}},exceptions:{hero:{recipe:'Button',properties:['padding'],reason:'Acme #1: extra room for "two lines".'}}};
const root = '<style>:root{--space-sm:8px;--space-md:16px;--radius-control:8px;--radius-large:16px;--color-ink:#202020;--color-accent:#0000ff;--size-title:24px;--size-display:32px;--weight-title:600}</style>';
const button = (style='padding:16px;border-radius:8px',attrs='')=>`<button data-isocan-recipe="Button" ${attrs} style="${style}">Acme action</button>`;
const tests=[];
const add=(name,html,expect,policy=lint)=>tests.push({name,html:root+html,expect,policy});
add('clean caller placement',button('padding:16px;border-radius:8px;margin:8px;align-self:center'),'clean');
add('valid token cannot override owned padding',button('padding:8px;border-radius:8px'),'ownership');
add('padding longhand cannot override shorthand',button('padding:16px;padding-top:8px;border-radius:8px'),'ownership');
add('radius second axis cannot evade ownership',button('padding:16px;border-radius:8px 8px 8px 8px / 8px 16px 8px 8px'),'ownership');
add('approved treatment',button('padding:8px;border-radius:8px','data-isocan-treatment="compact"'),'clean');
add('reasoned exception with on-scale padding',button('padding:8px;border-radius:8px','data-isocan-exception="hero"'),'clean');
add('exception does not allow off-scale padding',button('padding:13px;border-radius:8px','data-isocan-exception="hero"'),'finding');
add('unknown treatment',button('padding:16px;border-radius:8px','data-isocan-treatment="future"'),'finding');
add('unknown exception',button('padding:16px;border-radius:8px','data-isocan-exception="future"'),'finding');
add('title permits another declared size','<h1 data-isocan-recipe="Title" style="font-size:32px;font-weight:600">Acme title</h1>','clean');
add('title keeps owned weight','<h1 data-isocan-recipe="Title" style="font-size:32px;font-weight:700">Acme title</h1>','ownership');
add('font shorthand cannot hide owned weight','<h1 data-isocan-recipe="Title" style="font:700 32px sans-serif">Acme title</h1>','finding-or-unexamined');
add('missing owned declarations',button('margin:8px'),'finding');
add('caller property must be allowed',button('padding:16px;border-radius:8px;display:inline-flex'),'finding');
add('static class rule supported','<style>.acme{padding:16px;border-radius:8px}</style><button class="acme" data-isocan-recipe="Button">Acme action</button>','clean');
add('winning inline override checked','<style>.acme{padding:16px;border-radius:8px}</style><button class="acme" data-isocan-recipe="Button" style="padding:8px">Acme action</button>','ownership');
add('compound exact attribute selector supported','<style>button.acme[data-kind="action"]{padding:16px;border-radius:8px}</style><button class="acme" data-kind="action" data-isocan-recipe="Button">Acme action</button>','clean');
add('generic class has no recipe identity','<style>.Button{padding:8px;border-radius:8px}</style><button class="Button">Acme action</button>','clean');
const strict={...lint,literals:'require-references'};
add('strict exact literal',button(),'finding',strict);
add('strict real exported references',button('padding:var(--space-md);border-radius:var(--radius-control)'),'clean',strict);
add('strict true local alias',button('--local:var(--space-md);padding:var(--local);border-radius:var(--radius-control)'),'clean',strict);
add('strict literal local alias',button('--local:16px;padding:var(--local);border-radius:var(--radius-control)'),'finding',strict);
add('strict shadowed exported token','<p style="--color-ink:#0000ff;color:var(--color-ink)">Acme ink</p>','finding',strict);
add('unknown policy version',button(),'unexamined',{...lint,version:23});
add('unknown rule retained and unexamined',button(),'unexamined',{...lint,future:{enabled:true}});
add('external CSS not clean','<link rel="stylesheet" href="/missing.css">'+button(),'unexamined');
add('conditional ownership path not clean','<style>@media(min-width:10px){.acme{padding:8px}}</style><button class="acme" data-isocan-recipe="Button" style="padding:16px;border-radius:8px">Acme action</button>','unexamined');
add('radius allowance excludes border color','<p data-isocan-recipe="Acme" style="font-weight:600;border-color:#202020">Acme</p>','finding',{version:1,recipes:{Acme:{owns:{'font-weight':'600'},allow:['border-radius']}}});
add('partial padding ownership excludes undeclared sides','<p data-isocan-recipe="Acme" style="padding:16px 8px">Acme</p>','finding',{version:1,recipes:{Acme:{owns:{'padding-top':'16px'},allow:[]}}});
add('HTML attribute name case and important priority','<style>[DATA-KIND="action"]{padding:8px!important}</style><p data-kind="action" data-isocan-recipe="Acme" style="padding:16px">Acme</p>','ownership',{version:1,recipes:{Acme:{owns:{padding:'16px'},allow:[]}}});
for (const name of ['constructor','__proto__','toString']) add('inherited object name is no recipe: '+name,`<p data-isocan-recipe="${name}">Acme</p>`,'finding');
add('escaped class cannot hide important ownership override','<style>.acme\\:control{padding:8px!important}</style><button class="acme:control" data-isocan-recipe="Acme" style="padding:16px">Acme</button>','finding-or-unexamined',{version:1,recipes:{Acme:{owns:{padding:'16px'},allow:[]}}});
const results=[];
for(const t of tests){const report=auditScreen(t.html,{...base,isocan:{lint:t.policy}});const diagnostics=report.diagnostics; let pass=false; if(t.expect==='clean') pass=report.coverage.complete && diagnostics.length===0;
if(t.expect==='finding') pass=diagnostics.length>0;
if(t.expect==='ownership') pass=report.offSystem.length===0 && diagnostics.some(d=>d.code==='design/owned-value');
if(t.expect==='unexamined') pass=!report.coverage.complete;
if(t.expect==='finding-or-unexamined') pass=diagnostics.length>0||!report.coverage.complete;
for(const d of diagnostics){assert(d.range.start.offset>=0 && d.range.end.offset<=t.html.length);}
results.push({...t,pass,report});}
const output=process.argv[2] ?? '/tmp/isocan-contract-probe-results.json';await fs.writeFile(output,JSON.stringify({at:new Date().toISOString(),results},null,2));
console.log(JSON.stringify({output,passed:results.filter(x=>x.pass).length,total:results.length,failed:results.filter(x=>!x.pass).map(x=>({name:x.name,expect:x.expect,diagnostics:x.report.diagnostics,coverage:x.report.coverage,policy:x.report.policy}))},null,2));
if(results.some(x=>!x.pass))process.exitCode=1;
