// Independent synthetic phase 3 proof. Run from the repository with node --import tsx.
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {parseDesign,serializeDesign} from '../../../packages/core/src/designmd.ts';
import {toDtcg,fromDtcg,toCss} from '../../../packages/core/src/tokens.ts';
import {importDesign} from '../../../packages/core/src/designimport.ts';
import {compileDesignContract} from '../../../packages/core/src/design-contract.ts';
const baseline=JSON.parse(await fs.readFile(new URL('./contract-roundtrip-baseline-2026-09-14.json', import.meta.url),'utf8'));
const results=[];
for(const [name,data] of Object.entries(baseline)){const input=data.input;const source=serializeDesign(input,'Synthetic current round trip.');const doc=parseDesign(source);assert.deepEqual(doc.tokens,input);assert.deepEqual(doc.problems,[]);const dtcg=toDtcg(input);const back=fromDtcg(dtcg);const imported=importDesign(JSON.stringify(dtcg),'acme.tokens.json');assert.deepEqual(back.isocan,input.isocan);assert.deepEqual(imported.tokens.isocan,input.isocan);assert.match(toCss(input),/policies, recipes, exceptions.*not preserved/);results.push({name,source,native:doc.tokens,dtcg,restored:back,imported,baselinePreserved:data.preserved,preserved:true});}
const native={name:'Acme contract references',spacing:{sm:'8px',md:'16px'},rounded:{control:'8px'},typography:{title:{fontWeight:600,fontSize:'24px'}},isocan:{lint:{version:1,recipes:{Button:{owns:{padding:'{spacing.md}','border-radius':'{rounded.control}'},allow:['margin']},Title:{owns:{'font-weight':'{typography.title.fontWeight}'},allow:['font-size']}},exceptions:{hero:{recipe:'Button',properties:['padding'],reason:'Acme #1: "two lines"'}}},future:{enabled:true,unset:null,nested:[{reason:'Acme: #quotes',values:[true,false,null,0,'01','true']}]}}};
const dc=toDtcg(native);const imported=importDesign(JSON.stringify(dc),'acme.tokens.json');assert.deepEqual(compileDesignContract(imported.tokens).effective,compileDesignContract(native).effective);assert.deepEqual(imported.tokens.isocan,native.isocan);assert.deepEqual(imported.problems,[]);results.push({name:'working references after native DTCG import',native,dtcg:dc,imported,policy:compileDesignContract(imported.tokens),preserved:true});
for(const [name,source] of Object.entries({quotedList:'isocan:\n  future:\n    - "why: because"\n    - \'Acme #1: don\'\'t drop\'\n    - {"a": 1, "b": true}',duplicate:'isocan: {"future":1,"future":2}',anchor:'isocan:\n  future: &anchor value',blockReason:'isocan:\n  future: |\n    Acme #1'})){const doc=parseDesign(`---\n${source}\n---\n`);if(name==='quotedList'){assert.deepEqual(doc.problems,[]);assert.deepEqual(doc.tokens.isocan,{future:['why: because',"Acme #1: don't drop",{a:1,b:true}]});}else{assert(doc.problems.length>0);assert.throws(()=>serializeDesign(doc.tokens,''));assert.throws(()=>toDtcg(doc.tokens));}results.push({name,doc,preserved:name==='quotedList',conversionRefused:name!=='quotedList'});}
const output=process.argv[2] ?? '/tmp/isocan-contract-roundtrip-results.json';await fs.writeFile(output,JSON.stringify({at:new Date().toISOString(),results},null,2));console.log(JSON.stringify({output,passed:results.length,total:results.length}));
